/****************************************************************************
 * Copyright (c) 2023, CEA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef EOS_IPP_BICUBIC_PROPS_HXX_
#define EOS_IPP_BICUBIC_PROPS_HXX_

#include "EOS/API/EOS_properties.hxx"

// Which stored fields the bicubic interpolation of a property reads, besides
// the property itself. In a header because two sides have to agree on it:
// EOS_Ipp, which looks these fields up when it loads a database, and EOS_IGen,
// which has to know what a database needs to carry for a given property to be
// interpolated the way the finished one will be (cf. the temporary MED of
// EOS_IGen::make_properties).

namespace NEPTUNE_EOS
{
  // Maps a base thermodynamic property to its two first-derivative properties
  // (d_prop_d_p_h, d_prop_d_h_p) as generated by EOS_IGen (cf. therm_properties.hxx).
  // Returns false for properties with no known derivative pair: p, h themselves,
  // saturation/limit-curve properties, or properties that are already a derivative
  // (bicubic interpolation only applies to the base 2D thermodynamic properties).
  inline bool bicubic_derivative_properties(NEPTUNE::EOS_Property prop,
                                      NEPTUNE::EOS_Property &dp_prop,
                                      NEPTUNE::EOS_Property &dh_prop)
  {
    switch (prop)
    {
      case NEPTUNE::T:      dp_prop = NEPTUNE::d_T_d_p_h;      dh_prop = NEPTUNE::d_T_d_h_p;      return true;
      case NEPTUNE::rho:    dp_prop = NEPTUNE::d_rho_d_p_h;    dh_prop = NEPTUNE::d_rho_d_h_p;    return true;
      case NEPTUNE::u:      dp_prop = NEPTUNE::d_u_d_p_h;      dh_prop = NEPTUNE::d_u_d_h_p;      return true;
      case NEPTUNE::s:      dp_prop = NEPTUNE::d_s_d_p_h;      dh_prop = NEPTUNE::d_s_d_h_p;      return true;
      case NEPTUNE::mu:     dp_prop = NEPTUNE::d_mu_d_p_h;     dh_prop = NEPTUNE::d_mu_d_h_p;     return true;
      case NEPTUNE::lambda: dp_prop = NEPTUNE::d_lambda_d_p_h; dh_prop = NEPTUNE::d_lambda_d_h_p; return true;
      case NEPTUNE::cp:     dp_prop = NEPTUNE::d_cp_d_p_h;     dh_prop = NEPTUNE::d_cp_d_h_p;     return true;
      case NEPTUNE::cv:     dp_prop = NEPTUNE::d_cv_d_p_h;     dh_prop = NEPTUNE::d_cv_d_h_p;     return true;
      case NEPTUNE::sigma:  dp_prop = NEPTUNE::d_sigma_d_p_h;  dh_prop = NEPTUNE::d_sigma_d_h_p;  return true;
      case NEPTUNE::w:      dp_prop = NEPTUNE::d_w_d_p_h;      dh_prop = NEPTUNE::d_w_d_h_p;      return true;
      case NEPTUNE::g:      dp_prop = NEPTUNE::d_g_d_p_h;      dh_prop = NEPTUNE::d_g_d_h_p;      return true;
      case NEPTUNE::f:      dp_prop = NEPTUNE::d_f_d_p_h;      dh_prop = NEPTUNE::d_f_d_h_p;      return true;
      case NEPTUNE::pr:     dp_prop = NEPTUNE::d_pr_d_p_h;     dh_prop = NEPTUNE::d_pr_d_h_p;     return true;
      case NEPTUNE::beta:   dp_prop = NEPTUNE::d_beta_d_p_h;   dh_prop = NEPTUNE::d_beta_d_h_p;   return true;
      case NEPTUNE::gamma:  dp_prop = NEPTUNE::d_gamma_d_p_h;  dh_prop = NEPTUNE::d_gamma_d_h_p;  return true;
      default:     return false;
    }
  }

  // Maps a base thermodynamic property to its stored cross derivative
  // (d2_prop_d_p_d_h), when EOS_IGen computed it (cf. therm_properties.hxx).
  // Same eligible set as bicubic_derivative_properties() above.
  inline bool bicubic_cross_derivative_property(NEPTUNE::EOS_Property prop,
                                          NEPTUNE::EOS_Property &d2_prop)
  {
    switch (prop)
    {
      case NEPTUNE::T:      d2_prop = NEPTUNE::d2_T_d_p_d_h;      return true;
      case NEPTUNE::rho:    d2_prop = NEPTUNE::d2_rho_d_p_d_h;    return true;
      case NEPTUNE::u:      d2_prop = NEPTUNE::d2_u_d_p_d_h;      return true;
      case NEPTUNE::s:      d2_prop = NEPTUNE::d2_s_d_p_d_h;      return true;
      case NEPTUNE::mu:     d2_prop = NEPTUNE::d2_mu_d_p_d_h;     return true;
      case NEPTUNE::lambda: d2_prop = NEPTUNE::d2_lambda_d_p_d_h; return true;
      case NEPTUNE::cp:     d2_prop = NEPTUNE::d2_cp_d_p_d_h;     return true;
      case NEPTUNE::cv:     d2_prop = NEPTUNE::d2_cv_d_p_d_h;     return true;
      case NEPTUNE::sigma:  d2_prop = NEPTUNE::d2_sigma_d_p_d_h;  return true;
      case NEPTUNE::w:      d2_prop = NEPTUNE::d2_w_d_p_d_h;      return true;
      case NEPTUNE::g:      d2_prop = NEPTUNE::d2_g_d_p_d_h;      return true;
      case NEPTUNE::f:      d2_prop = NEPTUNE::d2_f_d_p_d_h;      return true;
      case NEPTUNE::pr:     d2_prop = NEPTUNE::d2_pr_d_p_d_h;     return true;
      case NEPTUNE::beta:   d2_prop = NEPTUNE::d2_beta_d_p_d_h;   return true;
      case NEPTUNE::gamma:  d2_prop = NEPTUNE::d2_gamma_d_p_d_h;  return true;
      default:              return false;
    }
  }
}

#endif
