/****************************************************************************
 * Copyright (c) 2023, CEA
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

/*
 * EOS_Ipp.cxx
 *
 *  Created on: 16 juin 2010
 */

#include "EOS_Ipp.hxx"
#include "EOS_Ipp_TileCache.hxx"
#include "EOS/API/EOS.hxx"
#include "EOS/API/EOS_Field.hxx"
#include "EOS/API/EOS_Fields.hxx"
#include "EOS/API/EOS_Config.hxx"
#include <cmath>
#include <fstream>
#include <iostream> // for std::cerr
#include <string>
#include <vector>
#define DBL_EPSILON 1e-9

namespace
{
  // Maps a base thermodynamic property to its two first-derivative properties
  // (d_prop_d_p_h, d_prop_d_h_p) as generated by EOS_IGen (cf. therm_properties.hxx).
  // Returns false for properties with no known derivative pair: p, h themselves,
  // saturation/limit-curve properties, or properties that are already a derivative
  // (bicubic interpolation only applies to the base 2D thermodynamic properties).
  bool bicubic_derivative_properties(NEPTUNE::EOS_Property prop,
                                      NEPTUNE::EOS_Property &dp_prop,
                                      NEPTUNE::EOS_Property &dh_prop)
  {
    switch (prop)
    {
      case NEPTUNE::T:      dp_prop = NEPTUNE::d_T_d_p_h;      dh_prop = NEPTUNE::d_T_d_h_p;      return true;
      case NEPTUNE::rho:    dp_prop = NEPTUNE::d_rho_d_p_h;    dh_prop = NEPTUNE::d_rho_d_h_p;    return true;
      case NEPTUNE::u:      dp_prop = NEPTUNE::d_u_d_p_h;      dh_prop = NEPTUNE::d_u_d_h_p;      return true;
      case NEPTUNE::s:      dp_prop = NEPTUNE::d_s_d_p_h;      dh_prop = NEPTUNE::d_s_d_h_p;      return true;
      case NEPTUNE::mu:     dp_prop = NEPTUNE::d_mu_d_p_h;     dh_prop = NEPTUNE::d_mu_d_h_p;     return true;
      case NEPTUNE::lambda: dp_prop = NEPTUNE::d_lambda_d_p_h; dh_prop = NEPTUNE::d_lambda_d_h_p; return true;
      case NEPTUNE::cp:     dp_prop = NEPTUNE::d_cp_d_p_h;     dh_prop = NEPTUNE::d_cp_d_h_p;     return true;
      case NEPTUNE::cv:     dp_prop = NEPTUNE::d_cv_d_p_h;     dh_prop = NEPTUNE::d_cv_d_h_p;     return true;
      case NEPTUNE::sigma:  dp_prop = NEPTUNE::d_sigma_d_p_h;  dh_prop = NEPTUNE::d_sigma_d_h_p;  return true;
      case NEPTUNE::w:      dp_prop = NEPTUNE::d_w_d_p_h;      dh_prop = NEPTUNE::d_w_d_h_p;      return true;
      case NEPTUNE::g:      dp_prop = NEPTUNE::d_g_d_p_h;      dh_prop = NEPTUNE::d_g_d_h_p;      return true;
      case NEPTUNE::f:      dp_prop = NEPTUNE::d_f_d_p_h;      dh_prop = NEPTUNE::d_f_d_h_p;      return true;
      case NEPTUNE::pr:     dp_prop = NEPTUNE::d_pr_d_p_h;     dh_prop = NEPTUNE::d_pr_d_h_p;     return true;
      case NEPTUNE::beta:   dp_prop = NEPTUNE::d_beta_d_p_h;   dh_prop = NEPTUNE::d_beta_d_h_p;   return true;
      case NEPTUNE::gamma:  dp_prop = NEPTUNE::d_gamma_d_p_h;  dh_prop = NEPTUNE::d_gamma_d_h_p;  return true;
      default:     return false;
    }
  }

  // Maps a base thermodynamic property to its stored cross derivative
  // (d2_prop_d_p_d_h), when EOS_IGen computed it (cf. therm_properties.hxx).
  // Same eligible set as bicubic_derivative_properties() above.
  bool bicubic_cross_derivative_property(NEPTUNE::EOS_Property prop,
                                          NEPTUNE::EOS_Property &d2_prop)
  {
    switch (prop)
    {
      case NEPTUNE::T:      d2_prop = NEPTUNE::d2_T_d_p_d_h;      return true;
      case NEPTUNE::rho:    d2_prop = NEPTUNE::d2_rho_d_p_d_h;    return true;
      case NEPTUNE::u:      d2_prop = NEPTUNE::d2_u_d_p_d_h;      return true;
      case NEPTUNE::s:      d2_prop = NEPTUNE::d2_s_d_p_d_h;      return true;
      case NEPTUNE::mu:     d2_prop = NEPTUNE::d2_mu_d_p_d_h;     return true;
      case NEPTUNE::lambda: d2_prop = NEPTUNE::d2_lambda_d_p_d_h; return true;
      case NEPTUNE::cp:     d2_prop = NEPTUNE::d2_cp_d_p_d_h;     return true;
      case NEPTUNE::cv:     d2_prop = NEPTUNE::d2_cv_d_p_d_h;     return true;
      case NEPTUNE::sigma:  d2_prop = NEPTUNE::d2_sigma_d_p_d_h;  return true;
      case NEPTUNE::w:      d2_prop = NEPTUNE::d2_w_d_p_d_h;      return true;
      case NEPTUNE::g:      d2_prop = NEPTUNE::d2_g_d_p_d_h;      return true;
      case NEPTUNE::f:      d2_prop = NEPTUNE::d2_f_d_p_d_h;      return true;
      case NEPTUNE::pr:     d2_prop = NEPTUNE::d2_pr_d_p_d_h;     return true;
      case NEPTUNE::beta:   d2_prop = NEPTUNE::d2_beta_d_p_d_h;   return true;
      case NEPTUNE::gamma:  d2_prop = NEPTUNE::d2_gamma_d_p_d_h;  return true;
      default:              return false;
    }
  }

  // Real roots of c3*x^3 + c2*x^2 + c1*x + c0 = 0, returned in ascending order.
  // Used by the bicubic h(p,T) inversion (the per-cell equation T(p,h) = T is
  // cubic in h at fixed p).
  //
  // Closed form (Cardano, trigonometric method for the three-real-root case);
  // a leading coefficient is treated as zero when negligible w.r.t. the largest
  // coefficient magnitude, degrading gracefully to the quadratic/linear case
  // (the linear case is exactly the bilinear inversion equation). A fully
  // degenerate equation (all coefficients negligible: e.g. saturation plateau
  // where T does not depend on h) reports no isolated root. Each closed-form
  // root is polished by a residual-guarded Newton step to reduce roundoff.
  // Returns the number of real roots stored in roots[] (0 to 3).
  int cubic_real_roots(double c3, double c2, double c1, double c0, double roots[3])
  {
    double scale = fabs(c3);
    if (fabs(c2) > scale) scale = fabs(c2);
    if (fabs(c1) > scale) scale = fabs(c1);
    if (fabs(c0) > scale) scale = fabs(c0);
    if (scale <= 0.)
      return 0;
    const double eps_coef = 1.e-12 * scale;

    int nb = 0;
    if (fabs(c3) <= eps_coef)
    {
      if (fabs(c2) <= eps_coef)
      {
        // Linear equation: c1*x + c0 = 0
        if (fabs(c1) <= eps_coef)
          return 0; // constant equation: no isolated root
        roots[nb++] = -c0 / c1;
      }
      else
      {
        // Quadratic equation: numerically stable form avoiding cancellation
        double disc = c1 * c1 - 4. * c2 * c0;
        if (disc < 0.)
          return 0;
        double sq = sqrt(disc);
        double q = -0.5 * (c1 + (c1 >= 0. ? sq : -sq));
        roots[nb++] = q / c2;
        roots[nb++] = (fabs(q) > 0.) ? c0 / q : q / c2;
      }
    }
    else
    {
      // General cubic: normalize to monic form, then depress with x = y - a/3
      double a = c2 / c3, b = c1 / c3, c = c0 / c3;
      double pdep = b - a * a / 3.;
      double qdep = 2. * a * a * a / 27. - a * b / 3. + c;
      double shift = -a / 3.;
      double delta = 0.25 * qdep * qdep + pdep * pdep * pdep / 27.;

      if (delta > 0.)
      {
        // One real root (Cardano)
        double sq = sqrt(delta);
        roots[nb++] = cbrt(-0.5 * qdep + sq) + cbrt(-0.5 * qdep - sq) + shift;
      }
      else if (pdep < 0.)
      {
        // Three real roots (possibly repeated): trigonometric method
        double r = 2. * sqrt(-pdep / 3.);
        double arg = 3. * qdep / (pdep * r);
        if (arg > 1.) arg = 1.;
        if (arg < -1.) arg = -1.;
        double theta = acos(arg) / 3.;
        const double two_pi_3 = 2. * M_PI / 3.;
        roots[nb++] = r * cos(theta) + shift;
        roots[nb++] = r * cos(theta - two_pi_3) + shift;
        roots[nb++] = r * cos(theta + two_pi_3) + shift;
      }
      else
      {
        // delta <= 0 with pdep >= 0 forces pdep = qdep = 0: triple root
        roots[nb++] = shift;
      }
    }

    // Newton polish (kept only if it reduces the residual)
    for (int i = 0; i < nb; i++)
    {
      double x = roots[i];
      double fx = ((c3 * x + c2) * x + c1) * x + c0;
      double dfx = (3. * c3 * x + 2. * c2) * x + c1;
      if (fabs(dfx) > 0.)
      {
        double xn = x - fx / dfx;
        double fxn = ((c3 * xn + c2) * xn + c1) * xn + c0;
        if (fabs(fxn) < fabs(fx))
          roots[i] = xn;
      }
    }

    // Ascending order (at most 3 values)
    for (int i = 0; i < nb - 1; i++)
      for (int j = i + 1; j < nb; j++)
        if (roots[j] < roots[i])
        {
          double tmp = roots[i];
          roots[i] = roots[j];
          roots[j] = tmp;
        }

    return nb;
  }
}

namespace NEPTUNE_EOS
{
  const AString EOS_Ipp::tablename("Interpolator");
  // Definition of internal errors in EOS_Ipp:
  // The following errors leads to EOS_Error=bad
  static const int EOS_Ipp_Error_base = 1000;
  const EOS_Internal_Error EOS_Ipp::OUT_OF_BOUNDS = EOS_Internal_Error(EOS_Ipp_Error_base + 0, EOS_Error::bad);
  const EOS_Internal_Error EOS_Ipp::INVERT_h_pT = EOS_Internal_Error(EOS_Ipp_Error_base + 1, EOS_Error::error);
  const EOS_Internal_Error EOS_Ipp::PROP_NOT_IN_DB = EOS_Internal_Error(EOS_Ipp_Error_base + 2, EOS_Error::error);
  const EOS_Internal_Error EOS_Ipp::MODEL_NOT_INIT = EOS_Internal_Error(EOS_Ipp_Error_base + 3, EOS_Error::error);
  void EOS_Ipp::describe_error(const EOS_Internal_Error ierr, AString &description) const
  {
    if (ierr == EOS_Internal_Error::OK)
      description = "ok";
    else if (ierr == OUT_OF_BOUNDS)
      description = "Value out of interpolation domain";
    else if (ierr == INVERT_h_pT)
      description = "Invert h(p,T) return no h value";
    else if (ierr == PROP_NOT_IN_DB)
      description = "Property values not in db file";
    else
    {
      description = "Error occured to database production with ";
      description += base_method;
      description += " method";
    }
  }

  const AString &EOS_Ipp::table_name() const
  {
    return tablename;
  }

  EOS_Ipp::EOS_Ipp() : r1_val(20, std::vector<double>(30, 0.0)),
                       r2_val(20, std::vector<double>(30, 0.0)),
                       nodes(3),
                       med_file("none"),
                       save_bound(0),
                       interp_method(BILINEAR),
                       nodes_ph(2),
                       nodes_sat(1),
                       nodes_lim(1),
                       val_prop_properties(0),
                       connect_ph(0),
                       index_conn_ph(0),
                       connect_sat(0),
                       connect_lim(0),
                       n_p_ph(0),
                       n_h_ph(0),
                       n_p_satlim(0)

  {
  }

  EOS_Ipp::~EOS_Ipp()
  {
    if (obj_fluid != nullptr)
    {
      delete obj_fluid;
    }
    delete tile_cache_;
  }

  static RegisteredClass &EOS_Ipp_create()
  {
    return *(new EOS_Ipp());
  }

  int EOS_Ipp::type_Id = (RegisterType("EOS_Ipp", "EOS_Fluid",
                                       "EOS Interpolator",
                                       sizeof(EOS_Ipp),
                                       EOS_Ipp_create));

  ostream &EOS_Ipp::print_On(ostream &stream) const
  {
    return stream;
  }

  istream &EOS_Ipp::read_On(istream &stream)
  {
    return stream;
  }

  const Type_Info &EOS_Ipp::get_Type_Info() const
  {
    return (Types_Info::instance())[type_Id];
  }

  // Extracts an optional ":bicubic"/":bilinear" suffix appended to the file name
  // (e.g. "raffinement_local_Cathare2:bicubic"), so callers can pick the
  // interpolation method through the usual EOS("EOS_Ipp", "...") factory string.
  // By default , the interpolation method is BICUBIC.
  void EOS_Ipp::extract_interpolation_method(AString &file_name)
  {
    interp_method = BICUBIC;
    char *raw = file_name.aschar();
    char *sep = strrchr(raw, ':');
    if (sep == NULL)
      return;

    AString suffix(sep + 1);
    *sep = '\0';

    if (suffix == "bicubic")
      interp_method = BICUBIC;
    else if (suffix == "bilinear")
      interp_method = BILINEAR;
    else
      cerr << "EOS_Ipp::init : unknown interpolation method suffix \"" << suffix.aschar()
           << "\", falling back to bilinear" << endl;
  }

  int EOS_Ipp::init(const Strings &strings)
  {
    AString desc_err;
    FluidStr = AString("unknown");
    int sz = strings.size();
    if (sz != 1)
    {
      cerr << " EOS_Ipp::init : Reference with size " << sz
           << " is not implemented for EOS_Ipp ! " << endl;
      assert(0);
      exit(-1);
      return EOS_Error::error;
    }

    // directory {DATA}/EOS_Ipp : med_file (or tiled-database manifest)
    AString &file_name = strings[0];
    extract_interpolation_method(file_name);
    if (iret_eos_data_dir)
      return EOS_Error::error;

    if (EOS_Ipp_TileIndex::is_manifest(std::string(file_name.aschar())))
      return init_tiled(file_name);

    AString path = eos_data_dir.c_str();
    path += "/EOS_Ipp/";
    path += file_name;
    return load_from_med_path(path);
  }

  // Historical, eager, whole-database loading body of init(const Strings&),
  // factored out so EOS_Ipp_TileCache can reuse it, unmodified, to load one
  // tile of a tiled database (cf. init()'s ".eosmm" manifest detection).
  EOS_Error EOS_Ipp::load_from_med_path(const AString &full_med_path)
  {
    EOS_Error errM;
    med_file = full_med_path;

    // get method and reference used to generate med file: file name == "EOS_Method"."Liquid".med
    AString base_name = full_med_path;
    char *raw = base_name.aschar();
    char *slash = strrchr(raw, '/');
    char *save_pt;
    method = strtok_r(slash ? slash + 1 : raw, ".", &save_pt);
    reference = strtok_r(NULL, ".", &save_pt);

    if (method == "eos_igen_qi")
    {
      method = "";
      reference = "";
    }

    // load med file
    EOS_Med med(med_file);
    errM = med.read_File();
    if (errM != EOS_Error::good)
    {
      cerr << "Error : Open med file" << endl;
      cerr << "Error : EOS_Med::read_File" << endl;
      cerr << "Error : EOS_Ipp::load_from_med_path" << endl;
      return errM;
    }

    AString header;
    errM = med.read_header(header);
    if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Med::read_header" << endl;
      cerr << "Error : EOS_Ipp::load_from_med_path" << endl;
      return errM;
    }
    AString hh = strtok(header.aschar(), ":");
    base_method = strtok(NULL, "/");
    base_reference = strtok(NULL, "/");

    errM = load_med_nodes(med);
    if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Ipp::load_from_med_path" << endl;
      return errM;
    }

    errM = load_med_champ(med);
    if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Ipp::load_med_champ" << endl;
      cerr << "Error : EOS_Ipp::load_from_med_path" << endl;
      return errM;
    }

    errM = load_med_scalar(med);
    errM = med.close_File();
    if (errM != EOS_Error::good)
    {
      cerr << "Error : Close med file" << endl;
      cerr << "Error : EOS_Med::close_File" << endl;
      cerr << "Error : EOS_Ipp::load_from_med_path" << endl;
      return errM;
    }

    // pretraitements (2D)
    if (index_conn_ph.size() != 0)
      f_mesh2r_mesh();

    if( connect_sat.size() != 0)
      f_mesh1r_mesh();
    return EOS_Error::ok;
  }

  // Tiled-database ("streaming") mode: file_name refers to an ".eosmm"
  // manifest instead of a single .med file. Rather than loading a whole
  // database eagerly like load_from_med_path(), this builds an
  // EOS_Ipp_TileCache that lazily loads only the (p,h) tiles later actually
  // queried through compute_prop_ph/compute_prop_p/compute_h_pT -- cf. the
  // guards at the top of those three methods, the only places tile_cache_
  // is consulted. The global (p,h,T) bounds are read from the manifest so
  // that get_p_min()/get_p_max()/... (unchanged, they just read pmin/pmax/
  // ...) keep reporting the domain of the whole tiled database, not of
  // whichever tile happened to be loaded last.
  int EOS_Ipp::init_tiled(AString file_name)
  {
    AString path = eos_data_dir.c_str();
    path += "/EOS_Ipp/";
    path += file_name;

    const std::string suffix = (interp_method == BICUBIC) ? "bicubic" : "bilinear";
    tile_cache_ = new EOS_Ipp_TileCache(std::string(path.aschar()), suffix);
    if (!tile_cache_->is_valid())
    {
      cerr << "Error : EOS_Ipp::init : invalid tiled database manifest " << path.aschar() << endl;
      delete tile_cache_;
      tile_cache_ = nullptr;
      return EOS_Error::error;
    }

    const EOS_Ipp_TileIndex &idx = tile_cache_->index();
    pmin = idx.pmin();
    pmax = idx.pmax();
    hmin = idx.hmin();
    hmax = idx.hmax();
    tmin = idx.tmin();
    tmax = idx.tmax();
    pcrit = idx.pcrit();
    hcrit = idx.hcrit();
    tcrit = idx.tcrit();
    pmin_ipp = pmin_cpt = pmin;
    pmax_ipp = pmax_cpt = pmax;
    hmin_ipp = hmin_cpt = hmin;
    hmax_ipp = hmax_cpt = hmax;
    tmin_ipp = tmin_cpt = tmin;
    tmax_ipp = tmax_cpt = tmax;

    return EOS_Error::ok;
  }

  //"values" contains properties to load
  int EOS_Ipp::init(const Strings &strings, const Strings &values)
  {
    EOS_Error errM;
    AString desc_err;
    FluidStr = AString("unknown");
    int sz = strings.size();
    if (sz != 1)
    {
      cerr << " EOS_Ipp::init : Reference with size " << sz << " is not implemented for EOS_Ipp ! " << endl;
      assert(0);
      exit(-1);
      return EOS_Error::error;
    }

    char *pshell;
    if ((pshell = getenv("NEPTUNE_EOS_DATA")))
      med_file = pshell;
    else if ((pshell = getenv("USER_EOS_DATA")))
      med_file = pshell;
    else
#ifdef EOS_DATA_DIR
      med_file = EOS_DATA_DIR;
#else
    {
      cerr << "Directory DATA is not set " << endl;
      exit(-1);
    }
#endif
    // directory {DATA}/EOS_Ipp : med_file
    med_file += "/EOS_Ipp/";
    // file : med_file
    AString &file_name = strings[0];
    extract_interpolation_method(file_name);
    med_file += file_name;

    // get method and reference used to generate med file: file name == "EOS_Method"."Liquid".med
    method = strtok(file_name.aschar(), ".");
    reference = strtok(NULL, ".");

    // load med file
    EOS_Med med(med_file);
    errM = med.read_File();
    if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Med::read_File" << endl;
      cerr << "Error : EOS_Ipp::init" << endl;
      return errM;
    }

    AString header;
    errM = med.read_header(header);
    if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Ipp::read_header" << endl;
      cerr << "Error : EOS_Ipp::init" << endl;
      return errM;
    }
    AString hh = strtok(header.aschar(), ":");
    base_method = strtok(NULL, "/");
    base_reference = strtok(NULL, "/");

    load_med_nodes(med);
    errM = load_med_champ(med, values);
    if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Ipp::load_med_champ" << endl;
      cerr << "Error : EOS_Ipp::init" << endl;
      return errM;
    }
    load_med_scalar(med);
    med.close_File();

    // pretraitements (2D)
    if (index_conn_ph.size() != 0)
      f_mesh2r_mesh();

    if( connect_sat.size() != 0)
      f_mesh1r_mesh();
    return EOS_Error::ok;
  }

  EOS_Error EOS_Ipp::init_model(const std::string &model_name, const std::string &fluid_name, bool switch_comp_sat, bool swch_calc_deriv_fld)
  {
    obj_fluid = new EOS(model_name.c_str(), fluid_name.c_str());
    switch_model = true;
    switch_comp_sat_ = switch_comp_sat;
    swch_calc_deriv_fld_ = swch_calc_deriv_fld;
    // If we use the compute_ function (for debug) : allows to retrieve the bounds of one simulation
    save_bound = 1;

    // Change the bounds of the ipp for the one of the fluid
    obj_fluid->get_h_min(hmin);
    obj_fluid->get_h_max(hmax);
    obj_fluid->get_T_min(tmin);
    obj_fluid->get_T_max(tmax);
    obj_fluid->get_p_min(pmin);
    obj_fluid->get_p_max(pmax);
    return EOS_Error::good;
  }

  EOS_Error EOS_Ipp::compute_(const EOS_Field &pp,
                              const EOS_Field &hh,
                              EOS_Fields &r,
                              EOS_Error_Field &errfield) const
  {
    if (save_bound == 1) // to be done only once
    {
      hmin_cpt = 100000.;
      hmax_cpt = 0.;
      tmin_cpt = 100000.;
      tmax_cpt = 0.;
      pmin_cpt = 1000000000.;
      pmax_cpt = 0.;
      save_bound = 0;
    }
    // Displaying the bounds for each calculation
    /* std::cout << "The min and max of the calculations are:" << endl;
    std::cout << "pmin: " << pmin_cpt << endl;
    std::cout << "pmax: " << pmax_cpt << endl;
    std::cout << "hmin: " << hmin_cpt << endl;
    std::cout << "hmax: " << hmax_cpt << endl;
    std::cout << "tmin: " << tmin_cpt << endl;
    std::cout << "tmax: " << tmax_cpt << endl;*/
    // Updating the bounds
    for (int pts = 0; pts < pp.size(); pts++)
    {
      pmin_cpt = min(pmin_cpt, pp.get_data()[pts]);
      pmax_cpt = max(pmax_cpt, pp.get_data()[pts]);
      if (hh.get_property_name() == "T")
      {
        tmin_cpt = min(tmin_cpt, hh.get_data()[pts]); // Be careful, sometimes H = T.
        tmax_cpt = max(tmax_cpt, hh.get_data()[pts]);
      }
      if (hh.get_property_name() == "h")
      {
        hmin_cpt = min(hmin_cpt, hh.get_data()[pts]); // Be careful, sometimes H = T.
        hmax_cpt = max(hmax_cpt, hh.get_data()[pts]);
      }
    }
    // std::vector<std::vector<double>> r1_val; // defined with size 20*30
    // std::vector<std::vector<double>> r2_val; // defined with size 20*30

    // EOS_Error err = EOS_Fluid::compute(pp, hh, r, errfield); // debug: does the computation still run?
    EOS_Error err2 = obj_fluid->compute(pp, hh, r, errfield);
    // Filling r1_val and r2_val
    for (int pts = 0; pts < pp.size(); pts++)
      for (int prop = 0; prop < r.size(); prop++)
        r1_val[prop][pts] = r[prop].get_data()[pts]; // debug: does the computation still run?
    // EOS_Error err2 = obj_fluid->compute(pp, hh, r, errfield);
    EOS_Error err = EOS_Fluid::compute(pp, hh, r, errfield);
    for (int pts = 0; pts < pp.size(); pts++)
      for (int prop = 0; prop < r.size(); prop++)
        r2_val[prop][pts] = r[prop].get_data()[pts];
    // compute the error for each prop and pts, and return the max
    double err_ipp_rp = 0;
    int propmax = 0;
    if (err == EOS_Error::good && err2 == EOS_Error::good)
    {
      for (int prop = 0; prop < r.size(); prop++)
      {
        if (r[prop].get_property_name() == "T") // Updating the bound of T
        {
          for (int pts = 0; pts < pp.size(); pts++)
          {
            tmin_cpt = min(tmin_cpt, r[prop].get_data()[pts]);
            tmax_cpt = max(tmax_cpt, r[prop].get_data()[pts]);
          }
        }
        if (r[prop].get_property_name() == "d_sigma_d_p_h") // Updating the bound of Td_sigma_d_p_h
        {
          std::cout << "computation of d_sigma_d_p_h err ipp " << err << " err model" << err2 << endl;
          std::cout << "value of ipp " << r1_val[prop][0] << "and fluid : " << r2_val[prop][0];
        }
        double err_ipp_rp_prop = 0;
        for (int pts = 0; pts < pp.size(); pts++)
          err_ipp_rp_prop = max(err_ipp_rp_prop, abs(2 * (r1_val[prop][pts] - r2_val[prop][pts]) / (r1_val[prop][pts]))); // relative error
        if (err_ipp_rp_prop > err_ipp_rp)
        {
          err_ipp_rp = err_ipp_rp_prop;
          propmax = prop;
        }
      }
      std::cout << " Number of prop :  " << r.size() << " Number of computations : " << pp.size() << endl;
      std::cout << "The error is " << err_ipp_rp << " for " << r[propmax].get_property_name() << endl;
    }
    else
    {
      std::cout << "Error in computation. err ipp " << err << " err model" << err2 << endl;
      return obj_fluid->compute(pp, hh, r, errfield);
    }
    return err2;
  }

  EOS_Error EOS_Ipp::compute_(const EOS_Field &p,
                              EOS_Fields &r,
                              EOS_Error_Field &errfield) const
  {

    // Displaying the bounds at each calculation
    std::cout << "The min and max of the calculations are:" << endl;
    std::cout << "pmin: " << pmin_cpt << endl;
    std::cout << "pmax: " << pmax_cpt << endl;
    // Updating the bounds
    for (int pts = 0; pts < p.size(); pts++)
    {
      pmin_cpt = min(pmin_cpt, p.get_data()[pts]);
      pmax_cpt = max(pmax_cpt, p.get_data()[pts]);
    }
    EOS_Error err = EOS_Fluid::compute(p, r, errfield);
    // Filling r1_val and r2_val
    for (int pts = 0; pts < p.size(); pts++)
      for (int prop = 0; prop < r.size(); prop++)
        r1_val[prop][pts] = r[prop].get_data()[pts];
    EOS_Error err2 = obj_fluid->compute(p, r, errfield);
    for (int pts = 0; pts < p.size(); pts++)
      for (int prop = 0; prop < r.size(); prop++)
        r2_val[prop][pts] = r[prop].get_data()[pts];
    // compute the error for each prop and pts, and return the max
    double err_ipp_rp = 0;
    int propmax = 0;
    for (int prop = 0; prop < r.size(); prop++)
    {
      double err_ipp_rp_prop = 0;
      for (int pts = 0; pts < p.size(); pts++)
        err_ipp_rp_prop = max(err_ipp_rp_prop, abs((r1_val[prop][pts] - r2_val[prop][pts]) / (1 * (r2_val[prop][pts] == 0) + r2_val[prop][pts])));
      if (err_ipp_rp_prop > err_ipp_rp)
      {
        err_ipp_rp = err_ipp_rp_prop;
        propmax = prop;
      }
    }
    std::cout << "The error is " << err_ipp_rp << " for " << r[propmax].get_property_name() << endl;
    std::cout << "The errors are :  IPP:" << err << "and FLUID : " << err2 << endl;
    return err2;
  }

  EOS_Error EOS_Ipp::compute(const EOS_Field &pp,
                             const EOS_Field &hh,
                             EOS_Fields &r,
                             EOS_Error_Field &errfield) const
  {
    EOS_Error err = EOS_Fluid::compute(pp, hh, r, errfield);
    if ((err != EOS_Error::good)) // if the calculation by ipp did not pass
    {
        std::cout << "Error detected : " << err << " ;";
        std::cout << "for the pair (" << pp.get_data()[0] << "," << hh.get_data()[0] << ") " << std::endl;
        //r.print_On(std::cout);
      if (obj_fluid == nullptr)
      {
        std::cerr << "Error: The interpolator fluid is not initialized. To continue the calculation, call the function init_model(). " << std::endl;
        return err;
      }
      err = obj_fluid->compute(pp, hh, r, errfield);
    }
    // errfield = EOS_Internal_Error::OK; 
    return err;
  }

  EOS_Error EOS_Ipp::compute(const EOS_Field &p,
                             EOS_Fields &r,
                             EOS_Error_Field &errfield) const
  {
    EOS_Error err = EOS_Fluid::compute(p, r, errfield);
    if ((err != EOS_Error::good)) // if the calculation by ipp did not pass
    {
      std::cout <<" Erreur EOS : " << err; 
      std::cout << "The point p= (" << p.get_data() << "), Did not produce a valid calculation. " << std::endl;
      r.print_On(std::cout);
      if (obj_fluid == nullptr)
      {
        std::cerr << "Error: The interpolator fluid is not initialized. To continue the calculation, call the function init_model().  " << std::endl;
        return err;
      }
      err = obj_fluid->compute(p, r, errfield);
    }
    return err;
  }

  // load all fields
  EOS_Error EOS_Ipp::load_med_nodes(EOS_Med &med)
  {
    EOS_Error errM;
    Strings names(0);
    ArrOfInt dim(0);
    int nb_nodes = 0;

    errM = med.get_Maillages_Infos(names, dim);
    if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Med::get_Maillages_Infos" << endl;
      return errM;
    }

    // for each mesh, get info
    int nb_ns = names.size();
    for (int i = 0; i < nb_ns; i++)
    {
      errM = med.get_entity_size(names[i], nb_nodes, MED_NODE, MED_NONE,
                                 MED_COORDINATE, MED_NO_CMODE);
      if (dim[i] == 1) // sat or spinodal
      {
        n_p_satlim.resize(nb_nodes);
        EOS_Field pf("P", "p",NEPTUNE::p, n_p_satlim);

        if (names[i] == "sat_domain") // saturation
        {
          nodes_sat[0] = pf;
          errM = med.get_nodes(names[i], dim[i], nodes_sat);
          if (errM != EOS_Error::good)
          {
            cerr << "Error : EOS_Med::get_nodes: Error in reading nodes of sat domain" << endl;
            return EOS_Error::error;
          }
          errM = med.get_Connectivity_1D(names[i], connect_sat);
          if (errM != EOS_Error::good)
          {
            cerr << "Error : EOS_Med::get_nodes: Error in reading connectivity nodes of sat domain" << endl;
            return EOS_Error::error;
          }
        }

        else if (names[i] == "lim_domain")
        {
          nodes_lim[0] = pf;
          errM = med.get_nodes(names[i], dim[i], nodes_lim);
          if (errM != EOS_Error::good)
          {
            cerr << "Error : EOS_Med::get_nodes: Error in reading nodes of lim domain" << endl;
            return EOS_Error::error;
          }
          errM = med.get_Connectivity_1D(names[i], connect_lim);
          if (errM != EOS_Error::good)
          {
            cerr << "Error : EOS_Med::get_nodes: Error in reading connectivity nodes of lim domain" << endl;
            return EOS_Error::error;
          }
        }

        else
        {
          cerr << "Error in loading saturation/spinodale values" << endl;
          return EOS_Error::error;
        }
      }

      else
      {
        n_p_ph.resize(nb_nodes);
        n_h_ph.resize(nb_nodes);

        EOS_Field pf("P", "p",NEPTUNE::p, n_p_ph);
        EOS_Field hf("h", "h",NEPTUNE::h, n_h_ph);

        nodes_ph[0] = pf;
        nodes_ph[1] = hf;

        errM = med.get_nodes(names[i], dim[i], nodes_ph);
        if (errM != EOS_Error::good)
        {
          cerr << "Error : EOS_Med::get_nodes" << endl;
          return EOS_Error::error;
        }

        errM = med.get_Connectivity_2D(names[i], index_conn_ph, connect_ph);
        if (errM != EOS_Error::good)
        {
          cerr << "Error : EOS_Med::get_Connectivity_2D" << endl;
          return EOS_Error::error;
        }
      }
    }

    return EOS_Error::good;
  }

  // load all fields (== all present properties)
  EOS_Error EOS_Ipp::load_med_champ(EOS_Med &med)
  {
    EOS_Error errM;
    int nb_champ = 0;
    int nprop_all = 0;
    errM = med.get_number_champ(nb_champ);
    if (nb_champ < 1)
    {
      cerr << "Error : Bad number of field" << endl;
      return EOS_Error::error;
    }
    else if (errM != EOS_Error::good)
    {
      cerr << "Error : EOS_Med::get_number_champ" << endl;
      return EOS_Error::error;
    }

    // correction jp march 2012: why nb_champ/2 ??
    // int vectorsz = nb_champ/2;
    int vectorsz = nb_champ / 2 + 1;
    all_prop_val.resize(vectorsz);
    all_err_val.resize(vectorsz);
    
    val_prop_properties.resize(NEPTUNE::lastLimProperty +1);
    err_segm_sat.resize(NEPTUNE::lastLimProperty + 1);
    err_cell_ph.resize(NEPTUNE::lastLimProperty + 1);
    err_segm_lim.resize(NEPTUNE::lastLimProperty + 1);
    for (int i = 0; i < nb_champ; i++)
    {
      AString name;
      AString m_ass;
      int nbcomp = 0;
      int type = 0;
      errM = med.get_Champ_Noeud_Infos(i, name, type, nbcomp, m_ass);
      if (errM != EOS_Error::good)
      {
        cerr << "Error : EOS_Med::get_Champ_Noeud_Infos" << endl;
        return EOS_Error::error;
      }

      if (type == 1) // float -> properties values
      {
        ArrOfDouble xval(nbcomp);
        all_prop_val[nprop_all] = xval;
        EOS_Property prop = gen_property_number(name.aschar());
        EOS_Field res(name.aschar(), name.aschar(),prop, all_prop_val[nprop_all]);
        errM = med.get_Champ_Noeud(name, res);
        if (errM != EOS_Error::good)
        {
          cerr << "Error : EOS_Med::get_Champ_Noeud" << endl;
          return EOS_Error::error;
        }
        val_prop_properties[prop] = res;
          
   
        nprop_all++;
      }

      else
      {
        ArrOfInt err(nbcomp);
        EOS_Error_Field errf(err);
        errM = med.get_ErrChamp_Noeud(name, errf);
        EOS_Property prop;
        if (errM != EOS_Error::good)
        {
          cerr << "EOS_Med::get_ErrChamp_Noeud" << endl;
          return EOS_Error::error;
        }
        if (name[0] == 'I' && name[1] == 'E')
        { // "IE propname" --> "propname"
          AString name_field = name;
          name_field.remove(0);
          name_field.remove(0);
          name_field.remove(0);
          errf.set_name(name_field.aschar());
          prop = gen_property_number(name_field.aschar());
        }
        else
        {
          errf.set_name(name.aschar());
          prop = gen_property_number(name.aschar());
        }


        if (m_ass == "ph_domain")
          node_err2mesh_err(prop,errf);
        else if (m_ass == "sat_domain")
          node_err2segm_err(prop,errf, 0);
        else if (m_ass == "lim_domain")
          node_err2segm_err(prop, errf, 1);
      }
    }

 //  std::cout << "Name of p: " << NEPTUNE::get_property_name(NEPTUNE::p) << "\n";
   // std::cout << "Name of h: " << NEPTUNE::get_property_name(NEPTUNE::h) << "\n";
    //std::cout << "Name of T: " << NEPTUNE::get_property_name(NEPTUNE::T) << "\n";
    //std::cout << "Unknown name: " << NEPTUNE::get_property_name(42) << "\n";
     // std::cout << "size ph: " << val_prop_properties.size() << "\n";


    return EOS_Error::good;
  }

  // selective load: only the fields requested by the user
  EOS_Error EOS_Ipp::load_med_champ(EOS_Med &med, const Strings &properties)
  {
    EOS_Error errM;
    int nb_champ = 0;
    errM = med.get_number_champ(nb_champ);
    if (nb_champ < 0)
    {
      cerr << "Error : Bad number of champs" << endl;
      return EOS_Error::error;
    }

    int nb_ps = properties.size();

    for (int i = 0; i < nb_champ; i++)
    {
      AString name;
      AString m_ass;
      int nbcomp = 0;
      int type = 0;
      errM = med.get_Champ_Noeud_Infos(i, name, type, nbcomp, m_ass);

      char namecov[PROPNAME_MSIZE];
      eostp_strcov(name.aschar(), namecov); // namecov : base alphanumerical property

      if (errM != EOS_Error::good)
      {
        cerr << "Error : EOS_Med::get_Champ_Noeud_Infos" << endl;
        return EOS_Error::error;
      }

      if (type == 1) // float -> properties values
      {              // get property values ?
        int j = 0;
        int found = 0;
        while (j < nb_ps && !found)
        {
          if (eostp_strcmp(properties[j].aschar(), namecov) == 0)
            found = 1;
          j++;
        }

        if (found)
        {
          ArrOfDouble xval(nbcomp);
          all_prop_val.push_back(xval);
          EOS_Property prop = gen_property_number(namecov);
          EOS_Field res(namecov, namecov,prop, all_prop_val[all_prop_val.size() - 1]);
          med.get_Champ_Noeud(name, res);
          val_prop_properties[prop] = res;

      }

      else
      { // get property values ?
        int j = 0;
        int found = 0;
        while (j < nb_ps && !found)
        {
          if (eostp_strcmp(properties[j].aschar(), namecov) == 0)
            found = 1;
          j++;
        }

        if (found)
        {
          ArrOfInt err(nbcomp);
          EOS_Error_Field errf(err);

          med.get_ErrChamp_Noeud(name, errf);
         
          errf.set_name(namecov);
          EOS_Property prop = gen_property_number(namecov);
          if (m_ass == "ph_domain")
            node_err2mesh_err(prop,errf);
          else if (m_ass == "sat_domain")
            node_err2segm_err(prop,errf, 0);
          else if (m_ass == "lim_domain")
            node_err2segm_err(prop, errf, 1);
        }
      }
    }
    }
    return EOS_Error::good;
  }

  EOS_Error EOS_Ipp::load_med_scalar(EOS_Med &med)
  {
    EOS_Error err;

    AString str_pmin("pmin");
    err = med.get_Scalar_Float(str_pmin, pmin);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  pmin scalar  in MED file" << endl;
      return err;
    }

    AString str_pmax("pmax");
    err = med.get_Scalar_Float(str_pmax, pmax);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  pmax scalar  in MED file" << endl;
      return err;
    }

    AString str_hmin("hmin");
    err = med.get_Scalar_Float(str_hmin, hmin);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  hmin scalar  in MED file" << endl;
      return err;
    }

    AString str_hmax("hmax");
    err = med.get_Scalar_Float(str_hmax, hmax);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  hmax scalar  in MED file" << endl;
      return err;
    }

    AString str_tmin("tmin");
    err = med.get_Scalar_Float(str_tmin, tmin);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  tmin scalar  in MED file" << endl;
      return err;
    }

    AString str_tmax("tmax");
    err = med.get_Scalar_Float(str_tmax, tmax);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  tmax scalar  in MED file" << endl;
      return err;
    }

    AString str_dp("delta_p");
    err = med.get_Scalar_Float(str_dp, delta_p_f);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  delta_p scalar  in MED file" << endl;
      return err;
    }

    nb_p_virtual = round((pmax - pmin) / delta_p_f);

    AString str_dh("delta_h");
    err = med.get_Scalar_Float(str_dh, delta_h_f);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  delta_h scalar  in MED file" << endl;
      return err;
    }

    nb_h_virtual = round((hmax - hmin) / delta_h_f);

    AString str_tcrit("tcrit");
    err = med.get_Scalar_Float(str_tcrit, tcrit);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  tcrit scalar  in MED file" << endl;
      return err;
    }

    AString str_pcrit("pcrit");
    err = med.get_Scalar_Float(str_pcrit, pcrit);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  pcrit scalar  in MED file" << endl;
      return err;
    }

    AString str_hcrit("hcrit");
    err = med.get_Scalar_Float(str_hcrit, hcrit);
    if (err != EOS_Error::good)
    {
      cerr << "EOS_Ipp::load_med_scalar : impossible to read  hcrit scalar  in MED file" << endl;
      return err;
    }

    // save of the bounds
    hmin_ipp = hmin;
    hmax_ipp = hmax;
    tmin_ipp = tmin;
    tmax_ipp = tmax;
    pmin_ipp = pmin;
    pmax_ipp = pmax;
    return err;
  }

  double EOS_Ipp::linear_interpolator(double p, const EOS_Ipp_CellData &segmval) const
  {
    // nodes
    //  fields[0] = 2 p values
    //  fields[1] = 2 property values
    //  p = p value of the point to interpolate
    //  res = interpolation result for the property (prop_name is in fields[1]

    // Interpolation formula
    // f(p*) = C1f1 + C2f2
    // with :   C1,C2 : value to compute
    //                          C1 = 1-p*
    //                          C2 = p*
    //                  f1,f2 : property value at C1 and C2
    //                  p* = (p-p1)/(p2-p1)

    double res;
    double C1, C2;
    double pcal;

    pcal = (p - segmval[0][0]) / (segmval[0][1] - segmval[0][0]);
    C1 = 1.e0 - pcal;
    C2 = pcal;

    res = C1 * segmval[1][0] + C2 * segmval[1][1];

    return res;
  }

 /* void EOS_Ipp::bilinear_interpolator(double p, double h, double &res) const
  {

    // nodes
    //  fields[0] = 4 p values
    //  fields[1] = 4 h values
    //  fields[2] = 4 property values (one per point)
    //  p = p value of the point to interpolate
    //  h = h value of the point to interpolate
    //  res = interpolation result for the property (prop_name is in fields[2]

    // Interpolation formula
    //  f(h*,p*) = sum(Cifi)
    //  with :    i = 1,...,4 == node
    //                   fi = property value at node i
    //                   Ci = to compute
    //                           C4 = h*p*
    //                           C3 = p* - C4
    //                           C2 = h* - C4
    //                           C1 = 1-p*-C2
    //                   p* = (p-p1)/(p3-p1)      => pcal
    //                   h* = (h-h1)/(h2-h1)      => hcal

    double C1, C2, C3, C4;
    double pcal, hcal;

    pcal = (p - nodes[0][0]) / (nodes[0][2] - nodes[0][0]);
    hcal = (h - nodes[1][0]) / (nodes[1][1] - nodes[1][0]);

    C4 = pcal * hcal;
    C3 = pcal - C4;
    C2 = hcal - C4;
    C1 = 1.e0 - pcal - C2;

    res = (C1 * nodes[2][0]) + (C2 * nodes[2][1]) + (C3 * nodes[2][2]) + (C4 * nodes[2][3]);
  }
*/
  double EOS_Ipp::bilinear_interpolator(double p, double h, const EOS_Ipp_CellData &cellval) const
  {
    // nodes
    //  fields[0] = 4 p values
    //  fields[1] = 4 h values
    //  fields[2] = 4 property values (one per point)
    //  p = p value of the point to interpolate
    //  h = h value of the point to interpolate
    //  res = interpolation result for the property (prop_name is in fields[2]

    // Interpolation formula
    //  f(h*,p*) = sum(Cifi)
    //  with :    i = 1,...,4 == node
    //                   fi = property value at node i
    //                   Ci = to compute
    //                           C4 = h*p*
    //                           C3 = p* - C4
    //                           C2 = h* - C4
    //                           C1 = 1-p*-C2
    //                   p* = (p-p1)/(p3-p1)      => pcal
    //                   h* = (h-h1)/(h2-h1)      => hcal

    double res;
    double C1, C2, C3, C4;
    double pcal, hcal;

    pcal = (p - cellval[0][0]) / (cellval[0][3] - cellval[0][0]);
    hcal = (h - cellval[1][0]) / (cellval[1][1] - cellval[1][0]);

    C3 = pcal * hcal;
    C4 = pcal - C3;
    C2 = hcal - C3;
    C1 = 1.e0 - pcal - C2;

    res = (C1 * cellval[2][0]) + (C2 * cellval[2][1]) + (C3 * cellval[2][2]) + (C4 * cellval[2][3]);

    return res;
  }

  void EOS_Ipp::bicubic_patch_data(const EOS_Ipp_CellData &cellval, bool has_cross_derivative,
                                    double f[4], double ft[4], double fu[4], double ftu[4]) const
  {
    // cellval rows (4 corners each, same corner ordering as bilinear_interpolator):
    //   [0] = p           [1] = h
    //   [2] = f  (property value)
    //   [3] = d f/dp |h   (property first derivative, at constant h)
    //   [4] = d f/dh |p   (property first derivative, at constant p)
    //   [5] = d2 f/dp.dh  (stored cross derivative, only read if has_cross_derivative)
    //
    // Corners in local unit-square coordinates (t=pcal, u=hcal):
    //   node0=(0,0)  node1=(0,1)  node2=(1,1)  node3=(1,0)
    //
    // The physical derivatives are scaled to the unit square
    // (d/dt = d/dp * dp, d/du = d/dh * dh). When the true cross derivative
    // d2f/dp.dh is available from the database (EOS_IGen), it is used directly.
    // Otherwise it is approximated locally (from the same 4 corners) as the
    // average of the two available one-sided finite differences of df/dp and
    // df/dh across the cell -- an approximation (not the exact mixed partial)
    // but one that requires no extra data and converges as the mesh is refined.

    double dp = cellval[0][3] - cellval[0][0];
    double dh = cellval[1][1] - cellval[1][0];

    for (unsigned short i = 0; i < 4; i++)
    {
      f[i] = cellval[2][i];
      ft[i] = cellval[3][i] * dp;
      fu[i] = cellval[4][i] * dh;
    }

    if (has_cross_derivative)
    {
      // d2F/dt.du = d2f/dp.dh * dp * dh
      for (unsigned short i = 0; i < 4; i++)
        ftu[i] = cellval[5][i] * dp * dh;
    }
    else
    {
      // Local twist estimate (see note above)
      ftu[0] = 0.5 * ((ft[1] - ft[0]) + (fu[3] - fu[0]));
      ftu[1] = 0.5 * ((ft[1] - ft[0]) + (fu[2] - fu[1]));
      ftu[2] = 0.5 * ((ft[2] - ft[3]) + (fu[2] - fu[1]));
      ftu[3] = 0.5 * ((ft[2] - ft[3]) + (fu[3] - fu[0]));
    }
  }

  double EOS_Ipp::bicubic_interpolator(double p, double h, const EOS_Ipp_CellData &cellval,
                                        bool has_cross_derivative) const
  {
    // Bicubic (tensor-product cubic Hermite) patch : matches f, df/dp and df/dh
    // exactly at the 4 corners (cf. bicubic_patch_data for the patch data and
    // the handling of the cross derivative).

    double p0 = cellval[0][0], p3 = cellval[0][3];
    double h0 = cellval[1][0], h1 = cellval[1][1];

    double pcal = (p - p0) / (p3 - p0);
    double hcal = (h - h0) / (h1 - h0);

    // Patch data in unit-square coordinates: corners 0=(0,0), 1=(0,1), 2=(1,1), 3=(1,0)
    double f[4], ft[4], fu[4], ftu[4];
    bicubic_patch_data(cellval, has_cross_derivative, f, ft, fu, ftu);

    // Cubic Hermite basis functions on [0,1]: H0/H1 for values, K0/K1 for slopes
    double t = pcal, t2 = t * t, t3 = t2 * t;
    double u = hcal, u2 = u * u, u3 = u2 * u;

    double Ht0 = 2. * t3 - 3. * t2 + 1.;
    double Ht1 = -2. * t3 + 3. * t2;
    double Kt0 = t3 - 2. * t2 + t;
    double Kt1 = t3 - t2;

    double Hu0 = 2. * u3 - 3. * u2 + 1.;
    double Hu1 = -2. * u3 + 3. * u2;
    double Ku0 = u3 - 2. * u2 + u;
    double Ku1 = u3 - u2;

    double res = Ht0 * Hu0 * f[0] + Ht0 * Hu1 * f[1] + Ht1 * Hu1 * f[2] + Ht1 * Hu0 * f[3]
               + Kt0 * Hu0 * ft[0] + Kt0 * Hu1 * ft[1] + Kt1 * Hu1 * ft[2] + Kt1 * Hu0 * ft[3]
               + Ht0 * Ku0 * fu[0] + Ht0 * Ku1 * fu[1] + Ht1 * Ku1 * fu[2] + Ht1 * Ku0 * fu[3]
               + Kt0 * Ku0 * ftu[0] + Kt0 * Ku1 * ftu[1] + Kt1 * Ku1 * ftu[2] + Kt1 * Ku0 * ftu[3];

    return res;
  }

  void EOS_Ipp::f_mesh1r_mesh()
  {
    unsigned int nb_p_nodes = round((pmax_ipp - pmin_ipp) /  delta_p_f);
    fnodes2pnodes.resize(nb_p_nodes);

    int nb_segm = connect_sat.size() / 2;

    for (int jseg = 0; jseg < nb_segm;jseg++)
    {
        double p_min_cell = nodes_sat[0][jseg];
        double p_max_cell = nodes_sat[0][jseg + 1];
        unsigned int i_p_min = round((p_min_cell - pmin_ipp)/ delta_p_f);
        unsigned int i_p_max = round((p_max_cell - pmin_ipp)/ delta_p_f);
      for (unsigned int i_p = i_p_min; i_p <i_p_max; i_p++)
      {
        fnodes2pnodes[i_p] = jseg;
      }
    }
    fnodes2pnodes_lim.resize(nb_p_nodes);

    nb_segm = connect_lim.size() / 2;

    for (int jseg = 0; jseg < nb_segm;jseg++)
    {
        double p_min_cell = nodes_lim[0][jseg];
        double p_max_cell = nodes_lim[0][jseg + 1];
        unsigned int i_p_min = round((p_min_cell - pmin_ipp)/ delta_p_f);
        unsigned int i_p_max = round((p_max_cell - pmin_ipp)/ delta_p_f);
      for (unsigned int i_p = i_p_min; i_p <i_p_max; i_p++)
      {
        fnodes2pnodes_lim[i_p] = jseg;
      }
    }
  }
  // correspondence between a fictitious node and 1 node of the polygon
  // The index value is stored to be able to retrieve the polygon in connect_ph
  // (the 4 nodes are needed for interpolation)
  // this approach should be revisited, not very robust (cf. condition for storing fnodes2phnodes[l])
  void EOS_Ipp::f_mesh2r_mesh()
  {
    unsigned int nb_cell = index_conn_ph.size() - 1;
    corners.resize(4 * nb_cell);

    unsigned int nb_h_nodes = round((hmax_ipp - hmin_ipp) / delta_h_f);
    unsigned int nb_p_nodes = round((pmax_ipp - pmin_ipp) / delta_p_f);

    fnodes2phnodes.resize(nb_h_nodes * nb_p_nodes);

    for (unsigned int i_med_cell = 0; i_med_cell < nb_cell; i_med_cell++)
    {
      unsigned int nb_node_in_cell = index_conn_ph[i_med_cell + 1] - index_conn_ph[i_med_cell];
      unsigned int num_first_node = index_conn_ph[i_med_cell];
      unsigned int node_1, node_2, node_3;
      unsigned int node_0 = connect_ph[num_first_node];

      // If the cell has more than 4 vertices, walk the vertices along the edges in
      // trigonometric order and recognize the first corner when P becomes constant, then
      // the second when h becomes constant, and the third when p becomes constant again
      if (nb_node_in_cell > 4)
      {
        unsigned int num_node_in_cell = num_first_node + 1;
        while (nodes_ph[0][num_node_in_cell] - nodes_ph[0][num_node_in_cell - 1] < DBL_EPSILON)
          num_node_in_cell++;
        node_1 = connect_ph[num_node_in_cell];

        while (nodes_ph[1][num_node_in_cell] - nodes_ph[1][num_node_in_cell - 1] < DBL_EPSILON)
          num_node_in_cell++;
        node_2 = connect_ph[num_node_in_cell];

        while (nodes_ph[0][num_node_in_cell] - nodes_ph[0][num_node_in_cell - 1] < DBL_EPSILON)
          num_node_in_cell++;
        node_3 = connect_ph[num_node_in_cell];
      }
      // If the cell has only 4 vertices, then they are the 4 corners of the cell
      else
      {
        node_1 = connect_ph[num_first_node + 1];
        node_2 = connect_ph[num_first_node + 2];
        node_3 = connect_ph[num_first_node + 3];
      }

      double p_min_cell = nodes_ph[0][node_0];
      double p_max_cell = nodes_ph[0][node_2];
      double h_min_cell = nodes_ph[1][node_0];
      double h_max_cell = nodes_ph[1][node_2];

      unsigned int i_p_min = round((p_min_cell - pmin_ipp) / delta_p_f);
      unsigned int i_p_max = round((p_max_cell - pmin_ipp) / delta_p_f);
      unsigned int i_h_min = round((h_min_cell - hmin_ipp) / delta_h_f);
      unsigned int i_h_max = round((h_max_cell - hmin_ipp) / delta_h_f);

      for (unsigned int i_p = i_p_min; i_p < i_p_max; i_p++)
      {
        for (unsigned int i_h = i_h_min; i_h < i_h_max; i_h++)
        {
          fnodes2phnodes[i_h + nb_h_nodes * i_p] = i_med_cell;
        }
      }

      corners[0 + 4 * i_med_cell] = node_0;
      corners[1 + 4 * i_med_cell] = node_1;
      corners[2 + 4 * i_med_cell] = node_2;
      corners[3 + 4 * i_med_cell] = node_3;
    }
  }

  void EOS_Ipp::node_err2mesh_err(EOS_Property prop,EOS_Error_Field &err_nodes_prop_ph)
  {
    int nb_cell = index_conn_ph.size() - 1;

    ArrOfInt err(nb_cell);
    all_err_val.push_back(err);
    EOS_Error_Field errf(all_err_val[all_err_val.size() - 1]);

    for (int j = 0; j < nb_cell; j++)
    { // Nodes number of the cell
      int nb_np = index_conn_ph[j + 1] - index_conn_ph[j];

      int nb;
      EOS_Internal_Error ierr1, ierr2, ierr3;
      int idx = index_conn_ph[j];

      ierr3 = err_nodes_prop_ph[connect_ph[idx]];
      nb = 1;

      while (nb < nb_np)
      {
        ierr1 = ierr3;
        ierr2 = err_nodes_prop_ph[connect_ph[idx + nb]];
        ierr3 = worst_internal_error(ierr1, ierr2);
        nb++;
      }
      errf.set(j, ierr3);
      errf.set_name(err_nodes_prop_ph.get_name().aschar());
    }
    err_cell_ph[prop] = new EOS_Error_Field(errf);
  }

  void EOS_Ipp::node_err2segm_err(EOS_Property prop,EOS_Error_Field &err_nodes_prop_p, int satlim)
  {
    int idx, idx2;

    if (satlim == 0)
    { // saturation
      int nb_segm = connect_sat.size() / 2;

      ArrOfInt nerr(nb_segm);
      all_err_val.push_back(nerr);
      EOS_Error_Field errf(all_err_val[all_err_val.size() - 1]);

      int k = 0;
      EOS_Internal_Error ierr1, ierr2;
      for (int j = 0; j < nb_segm; j++)
      {
        idx = connect_sat[k];
        idx2 = connect_sat[k + 1];
        ierr1 = err_nodes_prop_p[idx];
        ierr2 = err_nodes_prop_p[idx2];
        errf.set(j, worst_internal_error(ierr1, ierr2));
        k = k + 2;
      }
      err_segm_sat[prop] = new EOS_Error_Field(errf);
    }

    else
    { // spinodale
      int nb_segm = connect_lim.size() / 2;

      ArrOfInt nerr(nb_segm);
      all_err_val.push_back(nerr);
      EOS_Error_Field errf(all_err_val[all_err_val.size() - 1]);
      int k = 0;
      EOS_Internal_Error ierr1, ierr2;
      for (int j = 0; j < nb_segm; j++)
      {
        idx = connect_lim[k];
        idx2 = connect_lim[k];
        ierr1 = err_nodes_prop_p[idx];
        ierr2 = err_nodes_prop_p[idx2];
        errf.set(j, worst_internal_error(ierr1, ierr2));
        k = k + 2;
      }
      err_segm_lim[prop] = new EOS_Error_Field(errf);
    }
  }

  // returns the number of the actual cell containing (p, h)
  int EOS_Ipp::get_cellidx(double &p, double &h) const
  {
    unsigned int ih, ip;
    ih = (unsigned int)((h - hmin_ipp) / delta_h_f);
    ip = (unsigned int)((p - pmin_ipp) / delta_p_f);

    // if h or p respectively equal to hmax_ipp or pmax_ipp
    if (ip == nb_p_virtual)
      ip--;
    if (ih == nb_h_virtual)
      ih--;

    int i = nb_h_virtual * ip + ih;

    return fnodes2phnodes[i];
  }

  // Returns the real (med) cells whose p-range contains p, in ascending h
  // order -- the cell list scanned by the h(p,T) inversions (compute_h_l_pT,
  // compute_h_v_pT, compute_h_pT_bicubic).
  //
  // Instead of visiting every virtual row of the p-column (O(nb_h_virtual),
  // which can be huge on refined bases since delta_h_f is the finest cell
  // height), each identified cell is used to jump directly to the first
  // virtual row above its top edge, so the cost is O(number of real cells in
  // the column). The row index of a cell edge is recovered with the same
  // round() as f_mesh2r_mesh, so the jump lands exactly on the grid.
  //
  // Note: the historical scan collected the same cells in a
  // std::set<unsigned int>, i.e. iterated them by ascending med cell number;
  // the h-ascending order used here can only pick a different cell in the
  // degenerate case where several cells admit an inversion root (root exactly
  // on a shared edge), where both orders give an equivalent h.
  void EOS_Ipp::get_cells_containing_p(double p, std::vector<unsigned int> &cells) const
  {
    cells.clear();

    unsigned int ip = (unsigned int)((p - pmin_ipp) / delta_p_f);
    // if p equal to pmax_ipp (cf. get_cellidx)
    if (ip == nb_p_virtual)
      ip--;

    unsigned int ih = 0;
    while (ih < nb_h_virtual)
    {
      unsigned int cell = fnodes2phnodes[nb_h_virtual * ip + ih];
      cells.push_back(cell);

      // Jump to the first virtual row above the top edge of this cell
      double h_top = nodes_ph[1][corners[2 + 4 * cell]];
      unsigned int ih_next = (unsigned int)round((h_top - hmin_ipp) / delta_h_f);
      ih = (ih_next > ih) ? ih_next : ih + 1; // guaranteed progress
    }
  }

  /*
   * EOS_Ipp::get_segmidx :
   *      return index of first node of segment (index in nodes_sat/lim)
   *            (note = nodes in nodes_sat/lim are stored in ascending order)
   *
   * double& p  : intput p value
   * int     sat_lim  : sat or lim curve
   *
   * return : int (index)
   */
  int EOS_Ipp::get_segmidx(double &p, int sat_lim) const
  {
    unsigned int ip;
    if (sat_lim == 0)
    {
    ip = (unsigned int)((p - pmin_ipp) / delta_p_f);
    // if p respectively equal to pmax_ipp
    if (ip == nb_p_virtual)
      ip--;
    return fnodes2pnodes[ip];
    }
    else
    {
      ip = (unsigned int)((p - pmin_ipp) / delta_p_f);
    // if p respectively equal to pmax_ipp
    if (ip == nb_p_virtual)
      ip--;
    return fnodes2pnodes_lim[ip];
    }
  }


  // fetches the p, h and "property" values for the 4 points (=corners) of the actual cell
  //  idx = index in the med mesh = fnodes2phnodes[index_h + Nb_pts_h * index_p]
  EOS_Internal_Error EOS_Ipp::get_cell_values(int idx, EOS_Property i_prop, EOS_Ipp_CellData &cell_val) const
  {

    for (unsigned short i_node = 0; i_node < 4; i_node++)
    {
      int id_corn = corners[i_node + 4 * idx];
      cell_val[0][i_node] = nodes_ph[0][id_corn];
      cell_val[1][i_node] = nodes_ph[1][id_corn];
      cell_val[2][i_node] = val_prop_properties[i_prop][id_corn];
    }

    return (*err_cell_ph[i_prop])[idx].get_code();
  }

  bool EOS_Ipp::has_bicubic_first_derivative_data(EOS_Property prop) const
  {
    EOS_Property dp_prop, dh_prop;
    if (!bicubic_derivative_properties(prop, dp_prop, dh_prop))
      return false;

    int sz = (int)err_cell_ph.size();
    if (prop < 0 || prop >= sz || dp_prop < 0 || dp_prop >= sz || dh_prop < 0 || dh_prop >= sz)
      return false;

    return err_cell_ph[prop] != nullptr && err_cell_ph[dp_prop] != nullptr && err_cell_ph[dh_prop] != nullptr;
  }

  bool EOS_Ipp::has_bicubic_cross_derivative_data(EOS_Property prop) const
  {
    EOS_Property d2_prop;
    if (!bicubic_cross_derivative_property(prop, d2_prop))
      return false;

    int sz = (int)err_cell_ph.size();
    if (d2_prop < 0 || d2_prop >= sz)
      return false;

    return err_cell_ph[d2_prop] != nullptr;
  }

  // Fetches p, h, f and its two first derivatives (plus the stored cross
  // derivative if fetch_cross_derivative) for the 4 corners of the actual cell
  EOS_Internal_Error EOS_Ipp::get_cell_values_bicubic(int idx, EOS_Property i_prop, EOS_Ipp_CellData &cell_val,
                                                       bool fetch_cross_derivative) const
  {
    EOS_Property dp_prop, dh_prop;
    bicubic_derivative_properties(i_prop, dp_prop, dh_prop); // caller checked has_bicubic_first_derivative_data(i_prop)

    EOS_Property d2_prop = NEPTUNE::NotATProperty;
    if (fetch_cross_derivative)
      bicubic_cross_derivative_property(i_prop, d2_prop); // caller checked has_bicubic_cross_derivative_data(i_prop)

    for (unsigned short i_node = 0; i_node < 4; i_node++)
    {
      int id_corn = corners[i_node + 4 * idx];
      cell_val[0][i_node] = nodes_ph[0][id_corn];
      cell_val[1][i_node] = nodes_ph[1][id_corn];
      cell_val[2][i_node] = val_prop_properties[i_prop][id_corn];
      cell_val[3][i_node] = val_prop_properties[dp_prop][id_corn];
      cell_val[4][i_node] = val_prop_properties[dh_prop][id_corn];
      if (fetch_cross_derivative)
        cell_val[5][i_node] = val_prop_properties[d2_prop][id_corn];
    }

    EOS_Internal_Error ierr = (*err_cell_ph[i_prop])[idx].get_code();
    ierr = worst_internal_error(ierr, (*err_cell_ph[dp_prop])[idx].get_code());
    ierr = worst_internal_error(ierr, (*err_cell_ph[dh_prop])[idx].get_code());
    if (fetch_cross_derivative)
      ierr = worst_internal_error(ierr, (*err_cell_ph[d2_prop])[idx].get_code());
    return ierr;
  }

  EOS_Internal_Error EOS_Ipp::get_segm_values(int idx, EOS_Property i_prop, int sat_lim, EOS_Ipp_CellData &segm_val) const
  {
    if (sat_lim == 0)
    {


      segm_val[0][0] = nodes_sat[0][idx];
      segm_val[0][1] = nodes_sat[0][idx + 1];

      // property values
      segm_val[1][0] = val_prop_properties[i_prop][idx];
      segm_val[1][1] = val_prop_properties[i_prop][idx + 1];
      return  (*err_segm_sat[i_prop])[idx].get_code();

    }
    else
    {

      // p
      segm_val[0][0] = nodes_lim[0][idx];
      segm_val[0][1] = nodes_lim[0][idx + 1];
      // property values
      segm_val[1][0] = val_prop_properties[i_prop][idx];
      segm_val[1][1] = val_prop_properties[i_prop][idx + 1];
      return  (*err_segm_lim[i_prop])[idx].get_code();
    }
  }

  EOS_Internal_Error EOS_Ipp::compute_Ipp_error(double &error_tot, double *&error_cells, EOS_Property prop)
  {

    if (switch_model == false)
    {

      return MODEL_NOT_INIT;
    }
    unsigned int nb_cell = index_conn_ph.size() - 1;
    error_cells = new double[nb_cell];
    EOS_Ipp_CellData values;
    std::vector<int> error_eos(1, 0);
    NEPTUNE::EOS_Error_Field eos_error_field(1, &error_eos[0]);
    erreurtot = 0;
    double erreur_loc;
    //double vol_loc;
    long unsigned int nb_cell_pb = 0;
    ArrOfDouble ar_Ipp_bary(1);
    ArrOfDouble ar_fluid_bary(1);
    ArrOfDouble ap_bary(1);
    ArrOfDouble ah_bary(1);
    EOS_Field p_bary("P", "p",NEPTUNE::p, ap_bary);
    EOS_Field h_bary("h", "h",NEPTUNE::h, ah_bary);
    AString prop_string = get_property_name(prop);
    EOS_Field rf_fluid_bary(prop_string.aschar(), prop_string.aschar(),prop, ar_fluid_bary);
    // Retrieving the cell values

    for (unsigned int i_cell = 0; i_cell < nb_cell; i_cell++)
    {
      error_cells[i_cell] = 0;
      get_cell_values(i_cell, prop, values);
      const double *ap = values[0];
      const double *ah = values[1];
      // Compute barycenters and volumes
      ar_Ipp_bary[0] = 0; //
      ar_fluid_bary[0] = 0;
      //vol_loc = abs((ap[0] - ap[2]) * (ah[0] - ah[2]));
      ap_bary = (ap[0] + ap[1] + ap[2] + ap[3]) / 4;
      ah_bary = (ah[0] + ah[1] + ah[2] + ah[3]) / 4;
      // Compute with the fluid
      NEPTUNE::EOS_Error worst_liq = obj_fluid->compute(p_bary, h_bary, rf_fluid_bary, eos_error_field);
      NEPTUNE::EOS_Internal_Error worst_ipp = compute_prop_ph(prop, ap_bary[0], ah_bary[0], ar_Ipp_bary[0]);
      if ((worst_liq == 0) && (worst_ipp.get_code() == 0))
      {
        // Compute errors using the barycenter values
        /*if (abs(ar_Ipp_bary[0]-ar_fluid_bary[0])>10)
        {
          std::cout<<"computation problem for (p,h):" << ap_bary[0] <<","<<ah_bary[0] <<endl ;
          std::cout<<"The diff is " << abs(ar_Ipp_bary[0]-ar_fluid_bary[0])<<endl;
          std::cout << "The errors are: Ipp: " << worst_ipp.get_partial_code() << ", fluid: " << worst_liq<<endl;
          nb_cell_pb++;
        }
        else
        {*/
        // erreur_loc = (abs(ar_Ipp_bary[0] - ar_fluid_bary[0])) * vol_loc; // Error in L^1 norm
        erreur_loc = (abs(ar_Ipp_bary[0] - ar_fluid_bary[0])); // Local error, not accounting for cell area
        error_cells[i_cell] = erreur_loc;
        erreurtot += erreur_loc;
        //}
      }
      else
      {
        // std::cout<< "ipp error" << worst_ipp.get_code() << " and " << "fluid error: " << worst_liq << endl ;
        /*std::cout<<"computation problem for (p,h):" << ap_bary[0] <<","<<ah_bary[0] <<endl ; */
        nb_cell_pb++;
      }
    }
    // erreurtot = erreurtot / ((hmax_ipp - hmin_ipp) * (pmax_ipp - pmin_ipp)); // error normalization
    erreurtot = erreurtot / (nb_cell - nb_cell_pb); // error average
    error_tot = erreurtot;
    std::cout << "There were " << nb_cell_pb << " problematic cells out of " << nb_cell << ".";
    return EOS_Internal_Error::OK;
  }

  EOS_Internal_Error EOS_Ipp::compute_Ipp_sat_error(double &error_tot, double *&error_cells, EOS_Property prop)
  {

    if (switch_model == false)
    {
      std::cout << " Call the init_model() function.";
      return MODEL_NOT_INIT;
    }


    AString propname = NEPTUNE::get_property_name(prop);
    int nb_seg = nodes_sat[0].size();

    error_cells = new double[nb_seg];

    EOS_Ipp_CellData values;

    std::vector<int> error_eos(1, 0);
    NEPTUNE::EOS_Error_Field eos_error_field(1, &error_eos[0]);
    erreurtot = 0;
    double erreur_loc;
    double vol_loc;
    long unsigned int nb_seg_pb = 0;
    ArrOfDouble ar_Ipp_bary(1);
    ArrOfDouble ar_fluid_bary(1);
    ArrOfDouble ap_bary(1);
    EOS_Field p_bary("P", "p",NEPTUNE::p, ap_bary);
    EOS_Field rf_fluid_bary(propname.aschar(), propname.aschar(),prop, ar_fluid_bary);
    std::cout << "The number of nodes is " << nodes_sat[0].size() << endl;
    std::cout << "The number of segm is " << nb_seg << endl;
    std::cout << "Pmin= " << pmin_ipp << endl;
    std::cout << "Pmax= " << pmax_ipp << endl;
    // Retrieving the cell values
    for (int i_seg = 0; i_seg < nb_seg - 1; i_seg++)
    {
      error_cells[i_seg] = 0;
      get_segm_values(i_seg, prop, 0, values);
      const double *ap = values[0];
      // Compute barycenters and volumes
      ar_Ipp_bary[0] = 0; //
      ar_fluid_bary[0] = 0;
      vol_loc = abs((ap[1] - ap[0]));
      ap_bary = (ap[0] + ap[1]) / 2;
      // Compute with the fluid
      std::cout << "computing for (p,h):" << ap_bary[0] << "," << endl;
      NEPTUNE::EOS_Error worst_liq = obj_fluid->compute(p_bary, rf_fluid_bary, eos_error_field);
      NEPTUNE::EOS_Internal_Error worst_ipp = compute_prop_p(prop, ap_bary[0], 0, ar_Ipp_bary[0]);
      if ((worst_liq == 0) && (worst_ipp.get_code() == 0))
      {
        // Compute errors using the barycenter values
        /*if (abs(ar_Ipp_bary[0]-ar_fluid_bary[0])>10)
        {
          std::cout<<"computation problem for (p,h):" << ap_bary[0] <<","<<ah_bary[0] <<endl ;
          std::cout<<"The diff is " << abs(ar_Ipp_bary[0]-ar_fluid_bary[0])<<endl;
          std::cout << "The errors are: Ipp: " << worst_ipp.get_partial_code() << ", fluid: " << worst_liq<<endl;
          nb_cell_pb++;
        }
        else
        {*/

        std::cout << "The diff is " << abs(ar_Ipp_bary[0] - ar_fluid_bary[0]) << endl;
        erreur_loc = (abs(ar_Ipp_bary[0] - ar_fluid_bary[0])) * vol_loc;
        error_cells[i_seg] = erreur_loc;
        erreurtot += erreur_loc;
        //}
      }
      else
      {
        std::cout << "ipp error" << worst_ipp.get_code() << " and " << "fluid error: " << worst_liq << endl;
        /*std::cout<<"computation problem for (p,h):" << ap_bary[0] <<","<<ah_bary[0] <<endl ; */
        nb_seg_pb++;
      }
    }
    erreurtot = erreurtot / ((pmax_ipp - pmin_ipp)); // error normalization
    error_tot = erreurtot;
    std::cout << "There were " << nb_seg_pb << " problematic cells out of " << nb_seg << ".";
    return EOS_Internal_Error::OK;
  }

  EOS_Internal_Error EOS_Ipp::compute_h_pT(double p, double T, double &h) const
  {
    if (tile_cache_ != nullptr)
      return tile_cache_->compute_h_pT(p, T, h);

    h = NAN;
    double h_l_sat, h_v_sat, T_sat;
    EOS_Internal_Error ierr;
    EOS_Internal_Error ierrT, ierr1, ierr2, ierr3;

    ierr = check_p_bounds_ph(p);
    if (ierr == OUT_OF_BOUNDS)
      return ierr;

    ierrT = compute_T_sat_p(p, T_sat);
    if (ierrT != EOS_Internal_Error::OK)
      return ierrT;

    if (T <= T_sat)
    {
      ierr1 = compute_h_l_pT(p, T, h);
      ierr2 = compute_h_l_pT(p, T_sat, h_l_sat);
      ierr3 = worst_internal_error(ierr1, ierr2);
      if (std::isnan(h))
        return EOS_Internal_Error::EOS_BAD_COMPUTE; // If the computation of h failed
      if (h <= h_l_sat)
        return ierr3;
    }
    else
    {
      ierr1 = compute_h_v_pT(p, T, h);
      ierr2 = compute_h_v_pT(p, T_sat, h_v_sat);
      ierr3 = worst_internal_error(ierr1, ierr2);
      if (std::isnan(h))
        return ierr3; // If the computation of h failed
      if (h >= h_v_sat)
        return ierr3;
    }
    return INVERT_h_pT;
  }

  // Bicubic counterpart of the bilinear h(p,T) inversion of compute_h_l_pT /
  // compute_h_v_pT (cf. report Doc/Interpolator for the bilinear methodology,
  // reused here): all real cells whose p-range contains p are scanned, and in
  // each of them the equation T(p,h) = T is solved on the very same Hermite
  // patch as bicubic_interpolator, so that a subsequent direct evaluation
  // T(p, h(p,T)) in BICUBIC mode gives back the input T.
  //
  // How the bicubic coefficients are used: at fixed p (fixed t = pcal), the
  // tensor-product patch collapses to a 1D cubic Hermite polynomial in
  // u = hcal on [0,1],
  //     T(u) = A0*Hu0(u) + A1*Hu1(u) + D0*Ku0(u) + D1*Ku1(u)
  // where A0/A1 (edge values) and D0/D1 (edge u-derivatives) are obtained by a
  // 1D Hermite evaluation in t along the two edges u=0 and u=1. Written in
  // monomial form this is a cubic equation in u, solved in closed form
  // (cf. cubic_real_roots); a root is accepted when it lies in [0,1] with the
  // same boundary tolerance (DBL_EPSILON) as the bilinear inversion, and the
  // first (smallest) valid root of the first matching cell is returned, as in
  // the bilinear version. Degenerate cells in u (saturation plateau: T almost
  // independent of h) yield no isolated root and are skipped -- the bilinear
  // inversion skips them too (0/0 division -> NaN -> rejected by the [0,1]
  // test).
  //
  // Assumptions at the domain borders: no extrapolation is attempted; if no
  // scanned cell yields a root in [0,1], INVERT_h_pT is returned, exactly like
  // the bilinear inversion.
  EOS_Internal_Error EOS_Ipp::compute_h_pT_bicubic(double p, double T, double &res) const
  {
    EOS_Internal_Error ierr;
    bool has_cross_derivative = has_bicubic_cross_derivative_data(NEPTUNE::T);

    EOS_Ipp_CellData values;

    // Get all real cells containing p (same cell list as the bilinear inversion)
    std::vector<unsigned int> cells_containing_p;
    get_cells_containing_p(p, cells_containing_p);

    for (auto med_cell : cells_containing_p)
    {
      ierr = get_cell_values_bicubic(med_cell, NEPTUNE::T, values, has_cross_derivative);

      double pcal = (p - values[0][0]) / (values[0][3] - values[0][0]);

      // Patch data in unit-square coordinates: corners 0=(0,0), 1=(0,1), 2=(1,1), 3=(1,0)
      double f[4], ft[4], fu[4], ftu[4];
      bicubic_patch_data(values, has_cross_derivative, f, ft, fu, ftu);

      // 1D Hermite evaluation in t along the edges u=0 (corners 0,3) and u=1
      // (corners 1,2): values A0/A1 and u-derivatives D0/D1 of T at (t,u=0/1)
      double t = pcal, t2 = t * t, t3 = t2 * t;
      double Ht0 = 2. * t3 - 3. * t2 + 1.;
      double Ht1 = -2. * t3 + 3. * t2;
      double Kt0 = t3 - 2. * t2 + t;
      double Kt1 = t3 - t2;

      double A0 = Ht0 * f[0] + Ht1 * f[3] + Kt0 * ft[0] + Kt1 * ft[3];
      double A1 = Ht0 * f[1] + Ht1 * f[2] + Kt0 * ft[1] + Kt1 * ft[2];
      double D0 = Ht0 * fu[0] + Ht1 * fu[3] + Kt0 * ftu[0] + Kt1 * ftu[3];
      double D1 = Ht0 * fu[1] + Ht1 * fu[2] + Kt0 * ftu[1] + Kt1 * ftu[2];

      // Monomial coefficients of T(u) - T = 0, from
      // T(u) = A0*(2u^3-3u^2+1) + A1*(-2u^3+3u^2) + D0*(u^3-2u^2+u) + D1*(u^3-u^2)
      double c3 = 2. * (A0 - A1) + D0 + D1;
      double c2 = -3. * (A0 - A1) - 2. * D0 - D1;
      double c1 = D0;
      double c0 = A0 - T;

      double uroots[3];
      int nb_roots = cubic_real_roots(c3, c2, c1, c0, uroots);

      for (int k = 0; k < nb_roots; k++)
      {
        double hcal = uroots[k];
        if (((hcal > 0.0) || (fabs(hcal) < DBL_EPSILON)) && ((hcal < 1.0) || (fabs(hcal - 1.) < DBL_EPSILON)))
        {
          // hcal = (h-h1)/(h2-h1)   =>   h = hcal*(h2-h1)+h1;
          res = hcal * (values[1][1] - values[1][0]) + values[1][0];
          return EOS_Internal_Error::OK;
        }
      }
    }

    return EOS_Ipp::INVERT_h_pT;
  }

  EOS_Internal_Error EOS_Ipp::compute_h_l_pT(double p, double T, double &res) const
  {
    //    cout << "--- compute_h_l_pT p="<<p<<" T="<<T<<endl;

    // Bicubic inversion of h(p,T): only when the BICUBIC method is selected and
    // the T first-derivative fields are available in the loaded database;
    // otherwise the historical bilinear inversion below is used (same fallback
    // policy as compute_prop_ph).
    if (interp_method == BICUBIC && has_bicubic_first_derivative_data(NEPTUNE::T))
      return compute_h_pT_bicubic(p, T, res);

    EOS_Internal_Error ierr;
    double pcal, hcal, h;
    double a, b, c, d;

    pcal = hcal = h = 0.e0;

    EOS_Ipp_CellData values;
    EOS_Property prop = NEPTUNE::T;

    // Get all real cells containing p (ascending h order)
    std::vector<unsigned int> cells_containing_p;
    get_cells_containing_p(p, cells_containing_p);

    // read all cells containing p
    // for each cell compute h if 0<=h*<=1
    // return first h computed
    for (auto med_cell : cells_containing_p)
    {
      ierr = get_cell_values(med_cell, prop, values);
      pcal = (p - values[0][0]) / (values[0][2] - values[0][0]);

      /* a = values[2][1] - values[2][0];   // This computation doesn't correspond to the one on the report
      b = values[2][2] - values[2][0];
      c = values[2][3] - values[2][2] - a;
      d = values[2][0]; */ 
      

      a = values[2][1] - values[2][0];
      b = values[2][3] - values[2][0];
      c = values[2][2] - values[2][3] - a;
      d = values[2][0]; 


      hcal = (T - (b * pcal + d)) / (a + c * pcal);

      if (((hcal > 0.0) || (fabs(hcal) < DBL_EPSILON)) && ((hcal < 1.0) || (fabs(hcal - 1.) < DBL_EPSILON)))
      {
        // hcal = (h-h1)/(h2-h1)   =>   h = hcal*(h2-h1)+h1;
        res = hcal * (values[1][1] - values[1][0]) + values[1][0];
        return EOS_Internal_Error::OK;
      }
    }

    return EOS_Ipp::INVERT_h_pT;
  }

  EOS_Internal_Error EOS_Ipp::compute_h_v_pT(double p, double T, double &res) const
  {
    // Bicubic inversion of h(p,T): same policy as compute_h_l_pT above. The
    // liquid/vapor distinction is not made here (as in the bilinear inversion,
    // both scans cover the whole (p,h) mesh); it is handled by the caller
    // (compute_h_pT) through the comparison with the saturation enthalpies.
    if (interp_method == BICUBIC && has_bicubic_first_derivative_data(NEPTUNE::T))
      return compute_h_pT_bicubic(p, T, res);

    EOS_Internal_Error ierr;
    double pcal, hcal, h;
    double a, b, c, d;

    pcal = hcal = h = 0.0;

    EOS_Ipp_CellData values;
    EOS_Property prop = NEPTUNE::T;

    // Get all real cells containing p (ascending h order)
    std::vector<unsigned int> cells_containing_p;
    get_cells_containing_p(p, cells_containing_p);

    // read all cells containing p
    // for each cell compute h if 0<=h*<=1
    // return first h computed
    for (auto med_cell : cells_containing_p)
    {
      ierr = get_cell_values(med_cell,prop, values);
      pcal = (p - values[0][0]) / (values[0][2] - values[0][0]);
      /* a = values[2][1] - values[2][0];
      b = values[2][2] - values[2][0];
      c = values[2][3] - values[2][2] - a;
      d = values[2][0];*/ 
      a = values[2][1] - values[2][0];
      b = values[2][3] - values[2][0];
      c = values[2][2] - values[2][3] - a;
      d = values[2][0]; 


      hcal = (T - (b * pcal + d)) / (a + c * pcal);
      if (((hcal > 0.0) || (fabs(hcal) < DBL_EPSILON)) && ((hcal < 1.0) || (fabs(hcal - 1.) < DBL_EPSILON)))
      {
        // hcal = (h-h1)/(h2-h1)   =>   h = hcal*(h2-h1)+h1;
        res = hcal * (values[1][1] - values[1][0]) + values[1][0];
        return EOS_Internal_Error::OK;
      }
    }

    return EOS_Ipp::INVERT_h_pT;
  }

  EOS_Internal_Error EOS_Ipp::compute_prop_ph(EOS_Property prop,
                                              double p, double h, double &res) const
  {
    if (tile_cache_ != nullptr)
      return tile_cache_->compute_prop_ph(prop, p, h, res);

    // changer l'acces au prop
    EOS_Internal_Error ierr;

    ierr = check_ph_bounds(p, h);
    if (ierr == OUT_OF_BOUNDS)
      return ierr;

    int index = get_cellidx(p, h);

    // Bicubic Hermite patch, only if explicitly selected and the property has its
    // two first-derivative fields available in the loaded database; otherwise
    // (and for any property outside the 2D base-property set) fall back to the
    // historical bilinear path below. When the true stored cross derivative is
    // also available, it is used in place of the local finite-difference twist
    // estimate (cf. bicubic_interpolator) -- its absence alone never causes a
    // fallback to bilinear as long as the first derivatives are present.
    EOS_Ipp_CellData values;

    if (interp_method == BICUBIC && has_bicubic_first_derivative_data(prop))
    {
      bool has_cross_derivative = has_bicubic_cross_derivative_data(prop);

      ierr = get_cell_values_bicubic(index, prop, values, has_cross_derivative);
      if (ierr != EOS_Internal_Error::OK)
        return ierr;

      res = bicubic_interpolator(p, h, values, has_cross_derivative);
      return EOS_Internal_Error::OK;
    }

    ierr = get_cell_values(index, prop, values);
    if (ierr != EOS_Internal_Error::OK)
      return ierr;

    res = bilinear_interpolator(p, h, values);

    return EOS_Internal_Error::OK;
  }

  // tag = 0 for sat and tag = 1 for lim
  EOS_Internal_Error EOS_Ipp::compute_prop_p(EOS_Property prop,
                                             double p, int sat_lim, double &res) const
  {
    if (tile_cache_ != nullptr)
      return tile_cache_->compute_prop_p(prop, p, sat_lim, res);

    EOS_Internal_Error ierr;
    EOS_Ipp_CellData values;

    ierr = check_p_bounds_satlim(p);
    if (ierr == OUT_OF_BOUNDS)
      return ierr;

    int index = get_segmidx(p, sat_lim);
    ierr = get_segm_values(index, prop, sat_lim, values);

    res = linear_interpolator(p, values);

    return EOS_Internal_Error::OK;
  }

  EOS_Internal_Error EOS_Ipp::check_ph_bounds(double p, double h) const
  {
    EOS_Internal_Error ierr;
    if (std::isnan(h))
      return OUT_OF_BOUNDS;

    if ((fabs(h - hmin_ipp)) > DBL_EPSILON)
    //if ((fabs(h - hmin)) > DBL_EPSILON)
    {
      if (h < hmin_ipp)
      //if (h < hmin)
        return OUT_OF_BOUNDS;
    }

    if ((fabs(h - hmax_ipp) > DBL_EPSILON))
    //if ((fabs(h - hmax) > DBL_EPSILON))
    {
      // if ((h > hmax_ipp))
      if ((h > hmax_ipp))
        return OUT_OF_BOUNDS;
    }

    ierr = check_p_bounds_ph(p);
    return ierr;
  }

  EOS_Internal_Error EOS_Ipp::check_p_bounds_ph(double p) const
  {
    if ((fabs(p - pmin_ipp) > DBL_EPSILON))
    //if ((fabs(p - pmin) > DBL_EPSILON))
    {
      if ((p < pmin_ipp))
      //if ((p < pmin))
        return OUT_OF_BOUNDS;
    }

    if ((fabs(p - pmax_ipp) > DBL_EPSILON))
    //if ((fabs(p - pmax) > DBL_EPSILON))
    {
      if ((p > pmax_ipp))
      //if ((p > pmax))
        return OUT_OF_BOUNDS;
    }

    return EOS_Internal_Error::OK;
  }

  EOS_Internal_Error EOS_Ipp::check_p_bounds_satlim(double p) const
  {
    double max;

    if ((fabs(p - pmin_ipp) > DBL_EPSILON))
    //if ((fabs(p - pmin) > DBL_EPSILON))
    {
      if ((p < pmin_ipp))
      //if ((p < pmin))
        return OUT_OF_BOUNDS;
    }

    if (pcrit < pmax_ipp)
    //if (pcrit < pmax)
      max = pcrit;
    else
      max = pmax_ipp;
      //max = pmax;
    if ((fabs(p - max) > DBL_EPSILON))
    {
      if ((p > max))
        return OUT_OF_BOUNDS;
    }

    return EOS_Internal_Error::OK;
  }
}
