/****************************************************************************
* Copyright (c) 2023, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/

/*
 * main_ipp_bicubic.cxx
 *
 * Tests for the bicubic interpolation mode of EOS_Ipp:
 *  - method selection (default, ":bicubic"/":bilinear" suffix, setter override)
 *  - exact reproduction of the database at a mesh corner
 *  - accuracy on interior points vs. the reference fluid (and vs. bilinear)
 *  - out-of-bounds behaviour identical to bilinear
 *
 * Reuses the med databases generated by EOSIGenTest ("sans_raffinement_<Method>"),
 * built with the default (full) property list, which already includes the first
 * derivatives required by the bicubic patch (cf. therm_properties.hxx).
 */

#include "EOS/API/EOS.hxx"
#include "EOS/API/EOS_Config.hxx"
#include "EOS/Src/EOS_Ipp/EOS_Ipp.hxx"
#include "test_utils.hxx"

#include <cmath>
#include <iostream>

using namespace NEPTUNE;
using namespace NEPTUNE_EOS;

// Coarse 5x5 mesh (cf. EOS_IGen Tests/C++/main.cxx "sans_raffinement_") : bilinear
// error can reach a few percent, bicubic must stay markedly below it.
static const double REL_TOL_BILINEAR = 0.05;
static const double REL_TOL_BICUBIC  = 0.02;
static const double REL_TOL_EXACT    = 1.e-8; // at a mesh corner : direct database read

int main()
{
  cout << endl << "--------------------------------------- " << endl;
  cout <<         "------------ EOS_Ipp bicubic ----------- " << endl;
  cout <<         "--------------------------------------- " << endl;

  Language_init();

  bool test_failed = false;

  int nb_methodes = 0;
  Strings methodes(0);

#ifdef WITH_PLUGIN_THETIS
  nb_methodes = nb_methodes + 1;
  methodes.resize(nb_methodes);
  methodes[nb_methodes - 1] = "EOS_Thetis";
#endif
#ifdef WITH_PLUGIN_REFPROP_9
  nb_methodes = nb_methodes + 1;
  methodes.resize(nb_methodes);
  methodes[nb_methodes - 1] = "EOS_Refprop9";
#endif
#ifdef WITH_PLUGIN_CATHARE2
  nb_methodes = nb_methodes + 1;
  methodes.resize(nb_methodes);
  methodes[nb_methodes - 1] = "EOS_Cathare2";
#endif

  for (int m = 0; m < nb_methodes; m++)
  {
    cout << endl << "=== " << methodes[m] << " ===" << endl;

    AString base_file = "sans_raffinement_";
    base_file += methodes[m];

    // The 2-string EOS(method,reference) factory resolves the reference through
    // index.eos, which stores the on-disk file name (with its ".med" extension).
    // The ":bicubic"/":bilinear" suffixed names are not registered in index.eos,
    // so build those two through the (class name, Strings init_args) constructor,
    // which calls EOS_Ipp::init() directly, bypassing the index.eos lookup -- this
    // means the full on-disk file name (".med") must be supplied explicitly here.
    AString bicubic_file = base_file;
    bicubic_file += ".med:bicubic";

    AString bilinear_file = base_file;
    bilinear_file += ".med:bilinear";

    Strings bicubic_args(1);
    bicubic_args[0] = bicubic_file;
    Strings bilinear_args(1);
    bilinear_args[0] = bilinear_file;

    EOS obj_default("EOS_Ipp", base_file.aschar());
    EOS obj_bicubic("EOS_Ipp", bicubic_args);
    EOS obj_bilinear_expl("EOS_Ipp", bilinear_args);
    EOS obj_eos(methodes[m].aschar(), "WaterLiquid");

    EOS_Ipp &ipp_default       = dynamic_cast<EOS_Ipp &>(obj_default.fluid());
    EOS_Ipp &ipp_bicubic       = dynamic_cast<EOS_Ipp &>(obj_bicubic.fluid());
    EOS_Ipp &ipp_bilinear_expl = dynamic_cast<EOS_Ipp &>(obj_bilinear_expl.fluid());

    // ---- 1. Method selection ----
    if (ipp_default.get_interpolation_method() != EOS_Ipp::BILINEAR)
    {
      cerr << "ECHEC selection : no suffix should default to BILINEAR" << endl;
      test_failed = true;
    }
    if (ipp_bicubic.get_interpolation_method() != EOS_Ipp::BICUBIC)
    {
      cerr << "ECHEC selection : \":bicubic\" suffix should select BICUBIC" << endl;
      test_failed = true;
    }
    if (ipp_bilinear_expl.get_interpolation_method() != EOS_Ipp::BILINEAR)
    {
      cerr << "ECHEC selection : \":bilinear\" suffix should select BILINEAR" << endl;
      test_failed = true;
    }
    // programmatic override via the setter must take precedence
    ipp_bilinear_expl.set_interpolation_method(EOS_Ipp::BICUBIC);
    if (ipp_bilinear_expl.get_interpolation_method() != EOS_Ipp::BICUBIC)
    {
      cerr << "ECHEC selection : set_interpolation_method() should override the suffix" << endl;
      test_failed = true;
    }
    ipp_bilinear_expl.set_interpolation_method(EOS_Ipp::BILINEAR); // restore

    // ---- domain bounds (shared by the 3 databases : same underlying mesh) ----
    double pmin = 0., pmax = 0., hmin = 0., hmax = 0.;
    ipp_default.get_p_min(pmin);
    ipp_default.get_p_max(pmax);
    ipp_default.get_h_min(hmin);
    ipp_default.get_h_max(hmax);

    // ---- 2. Exact corner point (pmin,hmin) : both methods must reproduce the
    //         database value read directly from the mesh node ----
    {
      double T_ref, T_bilin, T_bicub;
      EOS_Error e_ref = obj_eos.compute_T_ph(pmin, hmin, T_ref);
      EOS_Internal_Error e_bilin = ipp_default.compute_T_ph(pmin, hmin, T_bilin);
      EOS_Internal_Error e_bicub = ipp_bicubic.compute_T_ph(pmin, hmin, T_bicub);

      if (e_ref != EOS_Error::good || e_bilin != EOS_Internal_Error::OK || e_bicub != EOS_Internal_Error::OK)
      {
        cerr << "ECHEC coin exact : erreur de calcul (ref=" << e_ref << ")" << endl;
        test_failed = true;
      }
      else if (!in_relative_range(T_bilin, T_ref, REL_TOL_EXACT) ||
               !in_relative_range(T_bicub, T_ref, REL_TOL_EXACT))
      {
        cerr << "ECHEC coin exact : T ref=" << T_ref << " bilineaire=" << T_bilin
             << " bicubique=" << T_bicub << endl;
        test_failed = true;
      }
    }

    // ---- 3. Interior points : accuracy vs. reference fluid, bicubic vs bilinear ----
    int n = 8;
    double max_err_bilin = 0., max_err_bicub = 0.;
    int nb_pts_ok = 0;

    for (int i = 1; i < n; i++)
    {
      double p = pmin + (pmax - pmin) * (double)i / (double)n;
      for (int j = 1; j < n; j++)
      {
        double h = hmin + (hmax - hmin) * (double)j / (double)n;

        double T_ref, T_bilin, T_bicub;
        EOS_Error e_ref = obj_eos.compute_T_ph(p, h, T_ref);
        EOS_Internal_Error e_bilin = ipp_default.compute_T_ph(p, h, T_bilin);
        EOS_Internal_Error e_bicub = ipp_bicubic.compute_T_ph(p, h, T_bicub);

        if (e_ref == EOS_Error::good && e_bilin == EOS_Internal_Error::OK && e_bicub == EOS_Internal_Error::OK)
        {
          nb_pts_ok++;
          double err_bilin = fabs(T_bilin - T_ref) / fabs(T_ref);
          double err_bicub = fabs(T_bicub - T_ref) / fabs(T_ref);
          max_err_bilin = max(max_err_bilin, err_bilin);
          max_err_bicub = max(max_err_bicub, err_bicub);
        }
      }
    }

    cout << "  interior points checked : " << nb_pts_ok << endl;
    cout << "  max relative error on T : bilinear=" << max_err_bilin
         << " ; bicubic=" << max_err_bicub << endl;

    if (nb_pts_ok == 0)
    {
      cerr << "ECHEC : aucun point interieur n'a pu etre calcule" << endl;
      test_failed = true;
    }
    if (max_err_bilin > REL_TOL_BILINEAR)
    {
      cerr << "ECHEC : erreur bilineaire hors tolerance (" << max_err_bilin << ")" << endl;
      test_failed = true;
    }
    if (max_err_bicub > REL_TOL_BICUBIC)
    {
      cerr << "ECHEC : erreur bicubique hors tolerance (" << max_err_bicub << ")" << endl;
      test_failed = true;
    }
    // small margin to absorb numerical noise while still requiring bicubic to be
    // at least as good as bilinear on this curved property
    if (max_err_bicub > max_err_bilin * 1.1 + 1.e-12)
    {
      cerr << "ECHEC : le bicubique n'ameliore pas la precision par rapport au bilineaire ("
           << max_err_bicub << " vs " << max_err_bilin << ")" << endl;
      test_failed = true;
    }

    // ---- 4. Domain edges : out-of-bounds behaviour identical to bilinear ----
    {
      double dummy;
      double p_oob = pmax + (pmax - pmin);
      EOS_Internal_Error e_bilin_oob = ipp_default.compute_T_ph(p_oob, hmin, dummy);
      EOS_Internal_Error e_bicub_oob = ipp_bicubic.compute_T_ph(p_oob, hmin, dummy);

      if (e_bilin_oob != EOS_Ipp::OUT_OF_BOUNDS || e_bicub_oob != EOS_Ipp::OUT_OF_BOUNDS)
      {
        cerr << "ECHEC bords : point hors domaine non signale en OUT_OF_BOUNDS "
             << "(bilineaire=" << e_bilin_oob.get_code() << ", bicubique=" << e_bicub_oob.get_code() << ")" << endl;
        test_failed = true;
      }
    }
  }

  cout << endl << "--------------------------------------- " << endl;
  cout <<         "---------------- End ------------------ " << endl;
  cout <<         "--------------------------------------- " << endl;

  Language_finalize();

  if (test_failed)
    return EXIT_FAILURE;
  return 0;
}
