/****************************************************************************
* Copyright (c) 2023, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/

/*
 * main_ipp_bicubic.cxx
 *
 * Tests for the bicubic interpolation mode of EOS_Ipp:
 *  - method selection (default, ":bicubic"/":bilinear" suffix, setter override)
 *  - exact reproduction of the database at a mesh corner
 *  - accuracy on interior points vs. the reference fluid (and vs. bilinear)
 *  - out-of-bounds behaviour identical to bilinear
 *  - presence of the stored cross derivative (d2_prop_d_p_d_h) in a base
 *    generated with the default (full) property list
 *  - numerical consistency of the fluid's cross derivative against a manual
 *    finite difference of its own first derivative
 *  - a base generated with a restricted property list (no cross derivative,
 *    but with the first derivatives) still uses the Hermite patch with its
 *    local twist approximation, not a silent fallback to bilinear
 *  - h(p,T) inversion (compute_h_pT -> compute_h_l_pT / compute_h_v_pT), for
 *    the liquid and vapor phases separately: consistency of the bicubic
 *    inversion with the direct bicubic evaluation T(p,h) (roundtrip), accuracy
 *    vs. the reference fluid compared to the bilinear inversion, no NaN inside
 *    the valid domain, controlled error codes outside of it
 *
 * Reuses the med databases generated by EOSIGenTest ("sans_raffinement_<Method>"),
 * built with the default (full) property list, which already includes the first
 * derivatives and the cross derivative required by the bicubic patch (cf.
 * therm_properties.hxx). The restricted-property base is generated locally,
 * on the fly, with the same EOS_IGen API used by EOSIGenTest.
 */

#include "EOS/API/EOS.hxx"
#include "EOS/API/EOS_Config.hxx"
#include "EOS/Src/EOS_Ipp/EOS_Ipp.hxx"
#include "EOS_IGen/API/EOS_IGen.hxx"
#include "test_utils.hxx"

#include <cmath>
#include <iostream>
#include <string>
#include <vector>

using namespace NEPTUNE;
using namespace NEPTUNE_EOS;
using namespace NEPTUNE_EOS_IGEN;

// Coarse 5x5 mesh (cf. EOS_IGen Tests/C++/main.cxx "sans_raffinement_") : bilinear
// error can reach a few percent, bicubic must stay markedly below it.
static const double REL_TOL_BILINEAR = 0.05;
static const double REL_TOL_BICUBIC  = 0.02;
static const double REL_TOL_EXACT    = 1.e-8; // at a mesh corner : direct database read

// h(p,T) inversion tolerances, relative to the h span of the base:
//  - roundtrip h -> T(p,h) -> h(p,T) on the same object must be near-exact
//    (analytic inversion of the very same interpolation surface);
//  - accuracy vs. the reference fluid is limited by the coarse mesh, same
//    order as the direct T(p,h) tolerances above.
static const double REL_TOL_ROUNDTRIP    = 1.e-8;
static const double REL_TOL_H_BILINEAR   = 0.05;
static const double REL_TOL_H_BICUBIC    = 0.02;

// Exercises the h(p,T) inversion of a phase-specific EOS_Ipp object
// (EOS_Ipp_liquid -> compute_h_l_pT, EOS_Ipp_vapor -> compute_h_v_pT, both
// through their public compute_h_pT) on the same database loaded in BILINEAR
// (ipp_bilin) and BICUBIC (ipp_bicub) mode, against the reference fluid
// obj_ref. Returns true if any check failed.
static bool test_h_pT_inversion(const char *phase, EOS_Ipp &ipp_bilin, EOS_Ipp &ipp_bicub,
                                EOS &obj_ref)
{
  bool failed = false;

  if (ipp_bicub.get_interpolation_method() != EOS_Ipp::BICUBIC ||
      ipp_bilin.get_interpolation_method() != EOS_Ipp::BILINEAR)
  {
    cerr << "FAILED h(p,T) " << phase << ": unexpected interpolation method" << endl;
    return true;
  }

  double pmin = 0., pmax = 0., hmin = 0., hmax = 0.;
  ipp_bilin.get_p_min(pmin);
  ipp_bilin.get_p_max(pmax);
  ipp_bilin.get_h_min(hmin);
  ipp_bilin.get_h_max(hmax);
  double h_span = hmax - hmin;

  int n = 8;
  int nb_roundtrip_ok = 0, nb_accuracy_ok = 0;
  double max_rt_bilin = 0., max_rt_bicub = 0.;
  double max_err_bilin = 0., max_err_bicub = 0.;
  bool bicubic_differs = false;

  for (int i = 1; i < n; i++)
  {
    double p = pmin + (pmax - pmin) * (double)i / (double)n;
    for (int j = 1; j < n; j++)
    {
      double h = hmin + h_span * (double)j / (double)n;

      // -- roundtrip on each interpolation surface: h -> T(p,h) -> h(p,T) --
      double T_bilin, T_bicub, h_rt_bilin, h_rt_bicub;
      EOS_Internal_Error eT1 = ipp_bilin.compute_T_ph(p, h, T_bilin);
      EOS_Internal_Error eT2 = ipp_bicub.compute_T_ph(p, h, T_bicub);
      EOS_Internal_Error eh1 = (eT1 == EOS_Internal_Error::OK)
                                   ? ipp_bilin.compute_h_pT(p, T_bilin, h_rt_bilin)
                                   : eT1;
      EOS_Internal_Error eh2 = (eT2 == EOS_Internal_Error::OK)
                                   ? ipp_bicub.compute_h_pT(p, T_bicub, h_rt_bicub)
                                   : eT2;

      if (eh1 == EOS_Internal_Error::OK && eh2 == EOS_Internal_Error::OK)
      {
        nb_roundtrip_ok++;
        if (std::isnan(h_rt_bilin) || std::isnan(h_rt_bicub))
        {
          cerr << "FAILED h(p,T) " << phase << ": NaN returned as OK at p=" << p
               << " T=" << T_bicub << endl;
          failed = true;
        }
        else
        {
          max_rt_bilin = max(max_rt_bilin, fabs(h_rt_bilin - h) / h_span);
          max_rt_bicub = max(max_rt_bicub, fabs(h_rt_bicub - h) / h_span);
          if (h_rt_bicub != h_rt_bilin)
            bicubic_differs = true;
        }
      }

      // -- accuracy vs. the reference fluid: T_ref = T_fluid(p,h), so the
      //    reference inverse of T_ref at this p is h itself --
      double T_ref, h_bilin, h_bicub;
      EOS_Error e_ref = obj_ref.compute_T_ph(p, h, T_ref);
      if (e_ref == EOS_Error::good)
      {
        EOS_Internal_Error e1 = ipp_bilin.compute_h_pT(p, T_ref, h_bilin);
        EOS_Internal_Error e2 = ipp_bicub.compute_h_pT(p, T_ref, h_bicub);
        if (e1 == EOS_Internal_Error::OK && e2 == EOS_Internal_Error::OK &&
            !std::isnan(h_bilin) && !std::isnan(h_bicub))
        {
          nb_accuracy_ok++;
          max_err_bilin = max(max_err_bilin, fabs(h_bilin - h) / h_span);
          max_err_bicub = max(max_err_bicub, fabs(h_bicub - h) / h_span);
        }
      }
    }
  }

  cout << "  h(p,T) " << phase << " : roundtrip points=" << nb_roundtrip_ok
       << " (max gap : bilinear=" << max_rt_bilin << " ; bicubic=" << max_rt_bicub << ")"
       << endl;
  cout << "  h(p,T) " << phase << " : accuracy points=" << nb_accuracy_ok
       << " (max relative error : bilinear=" << max_err_bilin
       << " ; bicubic=" << max_err_bicub << ")" << endl;

  if (nb_roundtrip_ok == 0 || nb_accuracy_ok == 0)
  {
    cerr << "FAILED h(p,T) " << phase << ": no point could be inverted" << endl;
    failed = true;
  }
  if (max_rt_bilin > REL_TOL_ROUNDTRIP || max_rt_bicub > REL_TOL_ROUNDTRIP)
  {
    cerr << "FAILED h(p,T) " << phase << ": inversion not consistent with the direct "
         << "evaluation (bilinear=" << max_rt_bilin << ", bicubic=" << max_rt_bicub << ")" << endl;
    failed = true;
  }
  if (max_err_bilin > REL_TOL_H_BILINEAR)
  {
    cerr << "FAILED h(p,T) " << phase << ": bilinear inversion error out of tolerance ("
         << max_err_bilin << ")" << endl;
    failed = true;
  }
  if (max_err_bicub > REL_TOL_H_BICUBIC)
  {
    cerr << "FAILED h(p,T) " << phase << ": bicubic inversion error out of tolerance ("
         << max_err_bicub << ")" << endl;
    failed = true;
  }
  // same margin as the direct-evaluation check: bicubic must not be worse
  if (max_err_bicub > max_err_bilin * 1.1 + 1.e-12)
  {
    cerr << "FAILED h(p,T) " << phase << ": bicubic inversion does not improve over "
         << "bilinear (" << max_err_bicub << " vs " << max_err_bilin << ")" << endl;
    failed = true;
  }
  if (!bicubic_differs)
  {
    cerr << "FAILED h(p,T) " << phase << ": BICUBIC inversion appears to degrade to "
         << "the bilinear inversion" << endl;
    failed = true;
  }

  // -- out-of-domain behaviour must stay controlled and identical to bilinear --
  {
    double dummy = 0.;
    double p_oob = pmax + (pmax - pmin);
    double p_mid = pmin + (pmax - pmin) * 0.5;
    double T_mid = 0.;
    ipp_bicub.compute_T_ph(p_mid, hmin + h_span * 0.5, T_mid);

    EOS_Internal_Error e1 = ipp_bilin.compute_h_pT(p_oob, T_mid, dummy);
    EOS_Internal_Error e2 = ipp_bicub.compute_h_pT(p_oob, T_mid, dummy);
    if (e1 != EOS_Ipp::OUT_OF_BOUNDS || e2 != EOS_Ipp::OUT_OF_BOUNDS)
    {
      cerr << "FAILED h(p,T) " << phase << ": p out of domain not reported as "
           << "OUT_OF_BOUNDS (bilinear=" << e1.get_code() << ", bicubic=" << e2.get_code()
           << ")" << endl;
      failed = true;
    }

    // T far above any temperature of the base: no h can be found, the
    // inversion must report INVERT_h_pT (no crash, no silent NaN)
    EOS_Internal_Error e3 = ipp_bilin.compute_h_pT(p_mid, 3000., dummy);
    EOS_Internal_Error e4 = ipp_bicub.compute_h_pT(p_mid, 3000., dummy);
    if (e3 != EOS_Ipp::INVERT_h_pT || e4 != EOS_Ipp::INVERT_h_pT)
    {
      cerr << "FAILED h(p,T) " << phase << ": unreachable T not reported as "
           << "INVERT_h_pT (bilinear=" << e3.get_code() << ", bicubic=" << e4.get_code()
           << ")" << endl;
      failed = true;
    }
  }

  return failed;
}

int main()
{
  cout << endl << "--------------------------------------- " << endl;
  cout <<         "------------ EOS_Ipp bicubic ----------- " << endl;
  cout <<         "--------------------------------------- " << endl;

  Language_init();

  bool test_failed = false;
  // Whether the cross derivative is picked up by EOS_IGen depends on the fluid
  // model being able to evaluate it (via a small perturbation) at the mesh's
  // representative point (a domain corner) -- some models are more sensitive
  // than others there. At least one of the tested fluids must succeed, to
  // prove the generation/storage/loading chain genuinely works end-to-end.
  bool any_cross_derivative_stored = false;

  int nb_methodes = 0;
  Strings methodes(0);

#ifdef WITH_PLUGIN_THETIS
  nb_methodes = nb_methodes + 1;
  methodes.resize(nb_methodes);
  methodes[nb_methodes - 1] = "EOS_Thetis";
#endif
#ifdef WITH_PLUGIN_REFPROP_9
  nb_methodes = nb_methodes + 1;
  methodes.resize(nb_methodes);
  methodes[nb_methodes - 1] = "EOS_Refprop9";
#endif
#ifdef WITH_PLUGIN_CATHARE2
  nb_methodes = nb_methodes + 1;
  methodes.resize(nb_methodes);
  methodes[nb_methodes - 1] = "EOS_Cathare2";
#endif

  for (int m = 0; m < nb_methodes; m++)
  {
    cout << endl << "=== " << methodes[m] << " ===" << endl;

    AString base_file = "sans_raffinement_";
    base_file += methodes[m];

    // The 2-string EOS(method,reference) factory resolves the reference through
    // index.eos, which stores the on-disk file name (with its ".med" extension).
    // The ":bicubic"/":bilinear" suffixed names are not registered in index.eos,
    // so build those two through the (class name, Strings init_args) constructor,
    // which calls EOS_Ipp::init() directly, bypassing the index.eos lookup -- this
    // means the full on-disk file name (".med") must be supplied explicitly here.
    AString bicubic_file = base_file;
    bicubic_file += ".med:bicubic";

    AString bilinear_file = base_file;
    bilinear_file += ".med:bilinear";

    Strings bicubic_args(1);
    bicubic_args[0] = bicubic_file;
    Strings bilinear_args(1);
    bilinear_args[0] = bilinear_file;

    EOS obj_default("EOS_Ipp", base_file.aschar());
    EOS obj_bicubic("EOS_Ipp", bicubic_args);
    EOS obj_bilinear_expl("EOS_Ipp", bilinear_args);
    EOS obj_eos(methodes[m].aschar(), "WaterLiquid");

    EOS_Ipp &ipp_default       = dynamic_cast<EOS_Ipp &>(obj_default.fluid());
    EOS_Ipp &ipp_bicubic       = dynamic_cast<EOS_Ipp &>(obj_bicubic.fluid());
    EOS_Ipp &ipp_bilinear_expl = dynamic_cast<EOS_Ipp &>(obj_bilinear_expl.fluid());

    // ---- 1. Method selection ----
    if (ipp_default.get_interpolation_method() != EOS_Ipp::BILINEAR)
    {
      cerr << "FAILED selection: no suffix should default to BILINEAR" << endl;
      test_failed = true;
    }
    if (ipp_bicubic.get_interpolation_method() != EOS_Ipp::BICUBIC)
    {
      cerr << "FAILED selection: \":bicubic\" suffix should select BICUBIC" << endl;
      test_failed = true;
    }
    if (ipp_bilinear_expl.get_interpolation_method() != EOS_Ipp::BILINEAR)
    {
      cerr << "FAILED selection: \":bilinear\" suffix should select BILINEAR" << endl;
      test_failed = true;
    }
    // programmatic override via the setter must take precedence
    ipp_bilinear_expl.set_interpolation_method(EOS_Ipp::BICUBIC);
    if (ipp_bilinear_expl.get_interpolation_method() != EOS_Ipp::BICUBIC)
    {
      cerr << "FAILED selection: set_interpolation_method() should override the suffix" << endl;
      test_failed = true;
    }
    ipp_bilinear_expl.set_interpolation_method(EOS_Ipp::BILINEAR); // restore

    // ---- domain bounds (shared by the 3 databases : same underlying mesh) ----
    double pmin = 0., pmax = 0., hmin = 0., hmax = 0.;
    ipp_default.get_p_min(pmin);
    ipp_default.get_p_max(pmax);
    ipp_default.get_h_min(hmin);
    ipp_default.get_h_max(hmax);

    // ---- 2. Exact corner point (pmin,hmin) : both methods must reproduce the
    //         database value read directly from the mesh node ----
    {
      double T_ref, T_bilin, T_bicub;
      EOS_Error e_ref = obj_eos.compute_T_ph(pmin, hmin, T_ref);
      EOS_Internal_Error e_bilin = ipp_default.compute_T_ph(pmin, hmin, T_bilin);
      EOS_Internal_Error e_bicub = ipp_bicubic.compute_T_ph(pmin, hmin, T_bicub);

      if (e_ref != EOS_Error::good || e_bilin != EOS_Internal_Error::OK || e_bicub != EOS_Internal_Error::OK)
      {
        cerr << "FAILED exact corner: computation error (ref=" << e_ref << ")" << endl;
        test_failed = true;
      }
      else if (!in_relative_range(T_bilin, T_ref, REL_TOL_EXACT) ||
               !in_relative_range(T_bicub, T_ref, REL_TOL_EXACT))
      {
        cerr << "FAILED exact corner: T ref=" << T_ref << " bilinear=" << T_bilin
             << " bicubic=" << T_bicub << endl;
        test_failed = true;
      }
    }

    // ---- 3. Interior points : accuracy vs. reference fluid, bicubic vs bilinear ----
    int n = 8;
    double max_err_bilin = 0., max_err_bicub = 0.;
    int nb_pts_ok = 0;

    for (int i = 1; i < n; i++)
    {
      double p = pmin + (pmax - pmin) * (double)i / (double)n;
      for (int j = 1; j < n; j++)
      {
        double h = hmin + (hmax - hmin) * (double)j / (double)n;

        double T_ref, T_bilin, T_bicub;
        EOS_Error e_ref = obj_eos.compute_T_ph(p, h, T_ref);
        EOS_Internal_Error e_bilin = ipp_default.compute_T_ph(p, h, T_bilin);
        EOS_Internal_Error e_bicub = ipp_bicubic.compute_T_ph(p, h, T_bicub);

        if (e_ref == EOS_Error::good && e_bilin == EOS_Internal_Error::OK && e_bicub == EOS_Internal_Error::OK)
        {
          nb_pts_ok++;
          double err_bilin = fabs(T_bilin - T_ref) / fabs(T_ref);
          double err_bicub = fabs(T_bicub - T_ref) / fabs(T_ref);
          max_err_bilin = max(max_err_bilin, err_bilin);
          max_err_bicub = max(max_err_bicub, err_bicub);
        }
      }
    }

    cout << "  interior points checked : " << nb_pts_ok << endl;
    cout << "  max relative error on T : bilinear=" << max_err_bilin
         << " ; bicubic=" << max_err_bicub << endl;

    if (nb_pts_ok == 0)
    {
      cerr << "FAILED: no interior point could be computed" << endl;
      test_failed = true;
    }
    if (max_err_bilin > REL_TOL_BILINEAR)
    {
      cerr << "FAILED: bilinear error out of tolerance (" << max_err_bilin << ")" << endl;
      test_failed = true;
    }
    if (max_err_bicub > REL_TOL_BICUBIC)
    {
      cerr << "FAILED: bicubic error out of tolerance (" << max_err_bicub << ")" << endl;
      test_failed = true;
    }
    // small margin to absorb numerical noise while still requiring bicubic to be
    // at least as good as bilinear on this curved property
    if (max_err_bicub > max_err_bilin * 1.1 + 1.e-12)
    {
      cerr << "FAILED: bicubic does not improve accuracy over bilinear ("
           << max_err_bicub << " vs " << max_err_bilin << ")" << endl;
      test_failed = true;
    }

    // ---- 4. Domain edges : out-of-bounds behaviour identical to bilinear ----
    {
      double dummy;
      double p_oob = pmax + (pmax - pmin);
      EOS_Internal_Error e_bilin_oob = ipp_default.compute_T_ph(p_oob, hmin, dummy);
      EOS_Internal_Error e_bicub_oob = ipp_bicubic.compute_T_ph(p_oob, hmin, dummy);

      if (e_bilin_oob != EOS_Ipp::OUT_OF_BOUNDS || e_bicub_oob != EOS_Ipp::OUT_OF_BOUNDS)
      {
        cerr << "FAILED bounds: out-of-domain point not reported as OUT_OF_BOUNDS "
             << "(bilinear=" << e_bilin_oob.get_code() << ", bicubic=" << e_bicub_oob.get_code() << ")" << endl;
        test_failed = true;
      }
    }

    // ---- 5. Cross derivative : presence in a full-property base, and numerical
    //         consistency against a manual finite difference ----
    {
      if (!ipp_bicubic.has_bicubic_first_derivative_data(NEPTUNE::rho))
      {
        cerr << "FAILED: the default base (full property list) should contain "
             << "rho's first derivatives" << endl;
        test_failed = true;
      }
      // The cross derivative itself is only picked up by EOS_IGen if the fluid
      // can evaluate it (a small p/h perturbation) at the mesh's representative
      // point (a domain corner) -- not guaranteed for every fluid/domain (some
      // models are more sensitive near the domain edge than others). Its
      // absence there is exactly the scenario the local-twist fallback exists
      // for (cf. section 6), so it is reported but not treated as a failure.
      bool has_cross = ipp_bicubic.has_bicubic_cross_derivative_data(NEPTUNE::rho);
      cout << "  cross derivative stored in the default base: " << (has_cross ? "yes" : "no") << endl;
      if (has_cross)
        any_cross_derivative_stored = true;

      double p_mid = pmin + (pmax - pmin) * 0.5;
      double h_mid = hmin + (hmax - hmin) * 0.5;
      double dh_fd = h_mid * 1.e-4; // step deliberately different from the internal epsilon (1e-6)

      double d1_minus, d1_plus, d2_impl;
      EOS_Internal_Error e1 = obj_eos.fluid().compute_d_rho_d_p_h_ph(p_mid, h_mid - dh_fd, d1_minus);
      EOS_Internal_Error e2 = obj_eos.fluid().compute_d_rho_d_p_h_ph(p_mid, h_mid + dh_fd, d1_plus);
      EOS_Internal_Error e3 = obj_eos.fluid().compute_d2_rho_d_p_d_h_ph(p_mid, h_mid, d2_impl);

      if (e1 == EOS_Internal_Error::OK && e2 == EOS_Internal_Error::OK && e3 == EOS_Internal_Error::OK)
      {
        double d2_manual = (d1_plus - d1_minus) / (2. * dh_fd);
        double denom = fabs(d2_manual) > 1.e-30 ? fabs(d2_manual) : 1.;
        double rel_err = fabs(d2_impl - d2_manual) / denom;
        cout << "  d2(rho)/dp.dh: implementation=" << d2_impl
             << " ; manual finite difference=" << d2_manual
             << " ; relative gap=" << rel_err << endl;
        if (rel_err > 1.e-2)
        {
          cerr << "FAILED numerical consistency d2_rho_d_p_d_h (gap=" << rel_err << ")" << endl;
          test_failed = true;
        }
      }
      else
      {
        cerr << "FAILED: could not compute d2_rho_d_p_d_h or its components "
             << "for the numerical consistency test" << endl;
        test_failed = true;
      }
    }

    // ---- 6. Compatibility with a base generated without the cross derivative
    //         (restricted property list) : BICUBIC must still use the Hermite
    //         patch (local twist approximation), not silently fall back to
    //         bilinear, as long as the first derivatives are present ----
    {
      AString restricted_name = "restricted_no_cross_";
      restricted_name += methodes[m];

      EOS_IGen obj_igen;
      obj_igen.set_method(methodes[m].aschar());
      obj_igen.set_reference("WaterLiquid");
      obj_igen.set_extremum(1.0e7, 2.0e7, 300., 500.);

      EOS_Error err = obj_igen.make_mesh(4, 4);
      vector<string> list_propi;
      list_propi.push_back("T");
      list_propi.push_back("rho");
      list_propi.push_back("d_T_d_p_h");
      list_propi.push_back("d_T_d_h_p");
      list_propi.push_back("d_rho_d_p_h");
      list_propi.push_back("d_rho_d_h_p");
      obj_igen.set_list_propi(list_propi);
      obj_igen.set_file_med_name(restricted_name);
      err = obj_igen.write_med();

      if (err != EOS_Error::good)
      {
        cerr << "FAILED: could not generate the restricted base (without cross derivative)" << endl;
        test_failed = true;
      }
      else
      {
        EOS obj_restricted("EOS_Ipp", restricted_name.aschar());
        EOS_Ipp &ipp_restricted = dynamic_cast<EOS_Ipp &>(obj_restricted.fluid());
        ipp_restricted.set_interpolation_method(EOS_Ipp::BICUBIC);

        if (!ipp_restricted.has_bicubic_first_derivative_data(NEPTUNE::rho))
        {
          cerr << "FAILED restricted base: first derivatives should be present" << endl;
          test_failed = true;
        }
        if (ipp_restricted.has_bicubic_cross_derivative_data(NEPTUNE::rho))
        {
          cerr << "FAILED restricted base: the cross derivative should not be present" << endl;
          test_failed = true;
        }

        double rp_min, rp_max, rh_min, rh_max;
        ipp_restricted.get_p_min(rp_min);
        ipp_restricted.get_p_max(rp_max);
        ipp_restricted.get_h_min(rh_min);
        ipp_restricted.get_h_max(rh_max);

        double p_mid = rp_min + (rp_max - rp_min) * 0.5;
        double h_mid = rh_min + (rh_max - rh_min) * 0.5;

        double rho_bicub_restricted, rho_bilin_restricted;
        EOS_Internal_Error eb = ipp_restricted.compute_rho_ph(p_mid, h_mid, rho_bicub_restricted);
        ipp_restricted.set_interpolation_method(EOS_Ipp::BILINEAR);
        EOS_Internal_Error el = ipp_restricted.compute_rho_ph(p_mid, h_mid, rho_bilin_restricted);

        if (eb != EOS_Internal_Error::OK || el != EOS_Internal_Error::OK)
        {
          cerr << "FAILED restricted base: rho computation failed" << endl;
          test_failed = true;
        }
        else if (rho_bicub_restricted == rho_bilin_restricted)
        {
          // On a curved property this would only coincide if BICUBIC had silently
          // degraded to the bilinear path instead of using the Hermite patch with
          // its local twist approximation.
          cerr << "FAILED restricted base: BICUBIC mode appears to degrade to "
               << "bilinear instead of using the local approximation" << endl;
          test_failed = true;
        }
      }
    }

    // ---- 7. h(p,T) inversion, liquid and vapor phases separately ----
    //
    // The phase-specific classes are used because their public compute_h_pT
    // goes straight to the inversion under test (EOS_Ipp_liquid ->
    // compute_h_l_pT, EOS_Ipp_vapor -> compute_h_v_pT), without the
    // saturation-enthalpy cross-checks of EOS_Ipp::compute_h_pT (whose
    // T_sat lies outside the T range of these single-phase bases).
    {
      // -- liquid : reuse the subcooled-liquid base of sections 1-5.
      //    EOS_Ipp::init consumes its Strings argument (the ":method" suffix and
      //    the ".med" extension are cut in place), so fresh Strings are rebuilt
      //    here instead of reusing bilinear_args/bicubic_args --
      AString liq_bicubic_file = base_file;
      liq_bicubic_file += ".med:bicubic";
      AString liq_bilinear_file = base_file;
      liq_bilinear_file += ".med:bilinear";

      Strings liq_bicubic_args(1);
      liq_bicubic_args[0] = liq_bicubic_file;
      Strings liq_bilinear_args(1);
      liq_bilinear_args[0] = liq_bilinear_file;

      EOS obj_liq_bilin("EOS_Ipp_liquid", liq_bilinear_args);
      EOS obj_liq_bicub("EOS_Ipp_liquid", liq_bicubic_args);
      EOS_Ipp &ipp_liq_bilin = dynamic_cast<EOS_Ipp &>(obj_liq_bilin.fluid());
      EOS_Ipp &ipp_liq_bicub = dynamic_cast<EOS_Ipp &>(obj_liq_bicub.fluid());

      if (test_h_pT_inversion("liquid", ipp_liq_bilin, ipp_liq_bicub, obj_eos))
        test_failed = true;

      // -- vapor : generate a superheated-steam base on the fly (same 5x5
      //    coarse mesh; T range above T_sat(pmax)=453 K on p in [1e5,1e6]),
      //    with the default (full) property list so the T derivatives needed
      //    by the bicubic inversion are stored --
      AString vapor_name = "vapor_h_pT_";
      vapor_name += methodes[m];

      EOS_IGen obj_igen_vap;
      obj_igen_vap.set_method(methodes[m].aschar());
      obj_igen_vap.set_reference("WaterVapor");
      obj_igen_vap.set_extremum(1.0e5, 1.0e6, 460., 700.);

      EOS_Error err_vap = obj_igen_vap.make_mesh(5, 5);
      if (err_vap == EOS_Error::good)
      {
        obj_igen_vap.set_file_med_name(vapor_name);
        err_vap = obj_igen_vap.write_med();
      }

      if (err_vap != EOS_Error::good)
      {
        cerr << "FAILED: could not generate the vapor base for the h(p,T) test" << endl;
        test_failed = true;
      }
      else
      {
        AString vap_bicubic_file = vapor_name;
        vap_bicubic_file += ".med:bicubic";
        AString vap_bilinear_file = vapor_name;
        vap_bilinear_file += ".med:bilinear";

        Strings vap_bicubic_args(1);
        vap_bicubic_args[0] = vap_bicubic_file;
        Strings vap_bilinear_args(1);
        vap_bilinear_args[0] = vap_bilinear_file;

        EOS obj_vap_bilin("EOS_Ipp_vapor", vap_bilinear_args);
        EOS obj_vap_bicub("EOS_Ipp_vapor", vap_bicubic_args);
        EOS_Ipp &ipp_vap_bilin = dynamic_cast<EOS_Ipp &>(obj_vap_bilin.fluid());
        EOS_Ipp &ipp_vap_bicub = dynamic_cast<EOS_Ipp &>(obj_vap_bicub.fluid());

        EOS obj_eos_vap(methodes[m].aschar(), "WaterVapor");

        if (test_h_pT_inversion("vapor", ipp_vap_bilin, ipp_vap_bicub, obj_eos_vap))
          test_failed = true;
      }
    }
  }

  if (nb_methodes > 0 && !any_cross_derivative_stored)
  {
    cerr << "FAILED: none of the tested fluids let EOS_IGen store the cross "
         << "derivative d2_rho_d_p_d_h -- the generation/loading chain appears "
         << "broken" << endl;
    test_failed = true;
  }

  cout << endl << "--------------------------------------- " << endl;
  cout <<         "---------------- End ------------------ " << endl;
  cout <<         "--------------------------------------- " << endl;

  Language_finalize();

  if (test_failed)
    return EXIT_FAILURE;
  return 0;
}
