/****************************************************************************
* Copyright (c) 2023, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/



// camix_properties.hxx

#ifndef CAMIX_PROPERTIES_H
#define CAMIX_PROPERTIES_H

namespace NEPTUNE
{ 
#if  __cplusplus >= 201103L
  static vector<typrop> camixprop =
#else
  static typrop t_camixprop[] =
#endif
    { {"c_0"                       ,   "vapor water mass fraction"                                  },
      {"c_1"                       ,   "n.1 incondensable gas mass fraction"                        },
      {"c_2"                       ,   "n.2 incondensable gas mass fraction"                        },
      {"c_3"                       ,   "n.3 incondensable gas mass fraction"                        },
      {"c_4"                       ,   "n.4 incondensable gas mass fraction"                        },
      {"P_0"                       ,   "vapor water partial pressure"                               },
      {"P_1"                       ,   "n.1 incondensable gas partial pressure"                     },
      {"P_2"                       ,   "n.2 incondensable gas partial pressure"                     },
      {"P_3"                       ,   "n.3 incondensable gas partial pressure"                     },
      {"P_4"                       ,   "n.4 incondensable gas partial pressure"                     },
      {"h_0"                       ,   "vapor water specific enthalpy"                              },
      {"h_1"                       ,   "n.1 incondensable gas specific enthalpy"                    },
      {"h_2"                       ,   "n.2 incondensable gas specific enthalpy"                    },
      {"h_3"                       ,   "n.3 incondensable gas specific enthalpy"                    },
      {"h_4"                       ,   "n.4 incondensable gas specific enthalpy"                    },
      {"T_0"                       ,   "vapor water Temperature"                                    },
      {"rho_0"                     ,   "vapor water density"                                        },
      {"u_0"                       ,   "vapor water specific internal energy"                       },
      {"s_0"                       ,   "vapor water specific entropy"                               },
      {"mu_0"                      ,   "vapor water dynamic viscosity"                              },
      {"lambda_0"                  ,   "vapor water thermal conductivity"                           },
      {"cp_0"                      ,   "vapor water specific isobaric heat capacity "               },
      {"sigma_0"                   ,   "vapor water surface tension"                                },
      {"w_0"                       ,   "vapor water speed of sound"                                 },
      {"g_0"                       ,   "vapor water specific free enthalpy"                         },
      {"f_0"                       ,   "vapor water specific free energy"                           },
      {"Pr_0"                      ,   "vapor water Prandtl number"                                 },
      {"beta_0"                    ,   "vapor water isobaric thermal expansion coefficient"         },
      {"gamma_0"                   ,   "vapor water cp / cv"                                        },
      {"T_sat_0"                   ,   "water Temperature at saturation"                            },
      {"rho_lsat_0"                ,   "liquid water density at saturation"                         },
      {"rho_vsat_0"                ,   "vapor  water density at saturation"                         },
      {"h_lsat_0"                  ,   "liquid water specific enthalpy at saturation"               },
      {"h_vsat_0"                  ,   "vapor  water specific enthalpy at saturation"               },
      {"cp_lsat_0"                 ,   "liquid water specific isobaric heat capacity at saturation" },
      {"cp_vsat_0"                 ,   "vapor  water specific isobaric heat capacity at saturation" },
      {"dncv"                      ,   "dncv"                                                       },
      {"rnc"                       ,   "rnc"                                                        },
      {"mnc"                       ,   "mnc"                                                        },
      {"xnc"                       ,   "xnc"                                                        },
      {"xvap"                      ,   "xvap"                                                       },
      {"prgr"                      ,   "prgr"                                                       },

      {"dT/d(c_0)_Ph"              ,   "dT/d(c_0)_Ph"                                               },
      {"d(T_0)/d(c_0)_Ph"          ,   "d(T_0)/d(c_0)_Ph"                                           },
      {"dT/d(c_1)_Ph"              ,   "dT/d(c_1)_Ph"                                               },
      {"d(T_0)/d(c_1)_Ph"          ,   "d(T_0)/d(c_1)_Ph"                                           },
      {"dT/d(c_2)_Ph"              ,   "dT/d(c_2)_Ph"                                               },
      {"d(T_0)/d(c_2)_Ph"          ,   "d(T_0)/d(c_2)_Ph"                                           },
      {"dT/d(c_3)_Ph"              ,   "dT/d(c_3)_Ph"                                               },
      {"d(T_0)/d(c_3)_Ph"          ,   "d(T_0)/d(c_3)_Ph"                                           },
      {"dT/d(c_4)_Ph"              ,   "dT/d(c_4)_Ph"                                               },
      {"d(T_0)/d(c_4)_Ph"          ,   "d(T_0)/d(c_4)_Ph"                                           },
      {"dT/d(P_0)_h"               ,   "dT/d(P_0)_h"                                                },
      {"dT/d(h_0)_P"               ,   "dT/d(h_0)_P"                                                },
      {"d(T_0)/dP_h"               ,   "d(T_0)/dP_h"                                                },
      {"d(T_0)/dh_P"               ,   "d(T_0)/dh_P"                                                },
      {"d(T_0)/d(P_0)_h"           ,   "d(T_0)/d(P_0)_h"                                            },
      {"d(T_0)/d(h_0)_P"           ,   "d(T_0)/d(h_0)_P"                                            },
      {"drho/d(c_0)_Ph"            ,   "drho/d(c_0)_Ph"                                             },
      {"d(rho_0)/d(c_0)_Ph"        ,   "d(rho_0)/d(c_0)_Ph"                                         },
      {"drho/d(c_1)_Ph"            ,   "drho/d(c_1)_Ph"                                             },
      {"d(rho_0)/d(c_1)_Ph"        ,   "d(rho_0)/d(c_1)_Ph"                                         },
      {"drho/d(c_2)_Ph"            ,   "drho/d(c_2)_Ph"                                             },
      {"d(rho_0)/d(c_2)_Ph"        ,   "d(rho_0)/d(c_2)_Ph"                                         },
      {"drho/d(c_3)_Ph"            ,   "drho/d(c_3)_Ph"                                             },
      {"d(rho_0)/d(c_3)_Ph"        ,   "d(rho_0)/d(c_3)_Ph"                                         },
      {"drho/d(c_4)_Ph"            ,   "drho/d(c_4)_Ph"                                             },
      {"d(rho_0)/d(c_4)_Ph"        ,   "d(rho_0)/d(c_4)_Ph"                                         },
      {"drho/d(P_0)_h"             ,   "drho/d(P_0)_h"                                              },
      {"drho/d(h_0)_P"             ,   "drho/d(h_0)_P"                                              },
      {"d(rho_0)/dP_h"             ,   "d(rho_0)/dP_h"                                              },
      {"d(rho_0)/dh_P"             ,   "d(rho_0)/dh_P"                                              },
      {"d(rho_0)/d(P_0)_h"         ,   "d(rho_0)/d(P_0)_h"                                          },
      {"d(rho_0)/d(h_0)_P"         ,   "d(rho_0)/d(h_0)_P"                                          },
      {"du/d(c_0)_Ph"              ,   "du/d(c_0)_Ph"                                               },
      {"d(u_0)/d(c_0)_Ph"          ,   "d(u_0)/d(c_0)_Ph"                                           },
      {"du/d(c_1)_Ph"              ,   "du/d(c_1)_Ph"                                               },
      {"d(u_0)/d(c_1)_Ph"          ,   "d(u_0)/d(c_1)_Ph"                                           },
      {"du/d(c_2)_Ph"              ,   "du/d(c_2)_Ph"                                               },
      {"d(u_0)/d(c_2)_Ph"          ,   "d(u_0)/d(c_2)_Ph"                                           },
      {"du/d(c_3)_Ph"              ,   "du/d(c_3)_Ph"                                               },
      {"d(u_0)/d(c_3)_Ph"          ,   "d(u_0)/d(c_3)_Ph"                                           },
      {"du/d(c_4)_Ph"              ,   "du/d(c_4)_Ph"                                               },
      {"d(u_0)/d(c_4)_Ph"          ,   "d(u_0)/d(c_4)_Ph"                                           },
      {"du/d(P_0)_h"               ,   "du/d(P_0)_h"                                                },
      {"du/d(h_0)_P"               ,   "du/d(h_0)_P"                                                },
      {"d(u_0)/dP_h"               ,   "d(u_0)/dP_h"                                                },
      {"d(u_0)/dh_P"               ,   "d(u_0)/dh_P"                                                },
      {"d(u_0)/d(P_0)_h"           ,   "d(u_0)/d(P_0)_h"                                            },
      {"d(u_0)/d(h_0)_P"           ,   "d(u_0)/d(h_0)_P"                                            },
      {"ds/d(c_0)_Ph"              ,   "ds/d(c_0)_Ph"                                               },
      {"d(s_0)/d(c_0)_Ph"          ,   "d(s_0)/d(c_0)_Ph"                                           },
      {"ds/d(c_1)_Ph"              ,   "ds/d(c_1)_Ph"                                               },
      {"d(s_0)/d(c_1)_Ph"          ,   "d(s_0)/d(c_1)_Ph"                                           },
      {"ds/d(c_2)_Ph"              ,   "ds/d(c_2)_Ph"                                               },
      {"d(s_0)/d(c_2)_Ph"          ,   "d(s_0)/d(c_2)_Ph"                                           },
      {"ds/d(c_3)_Ph"              ,   "ds/d(c_3)_Ph"                                               },
      {"d(s_0)/d(c_3)_Ph"          ,   "d(s_0)/d(c_3)_Ph"                                           },
      {"ds/d(c_4)_Ph"              ,   "ds/d(c_4)_Ph"                                               },
      {"d(s_0)/d(c_4)_Ph"          ,   "d(s_0)/d(c_4)_Ph"                                           },
      {"ds/d(P_0)_h"               ,   "ds/d(P_0)_h"                                                },
      {"ds/d(h_0)_P"               ,   "ds/d(h_0)_P"                                                },
      {"d(s_0)/dP_h"               ,   "d(s_0)/dP_h"                                                },
      {"d(s_0)/dh_P"               ,   "d(s_0)/dh_P"                                                },
      {"d(s_0)/d(P_0)_h"           ,   "d(s_0)/d(P_0)_h"                                            },
      {"d(s_0)/d(h_0)_P"           ,   "d(s_0)/d(h_0)_P"                                            },
      {"dmu/d(c_0)_Ph"             ,   "dmu/d(c_0)_Ph"                                              },
      {"d(mu_0)/d(c_0)_Ph"         ,   "d(mu_0)/d(c_0)_Ph"                                          },
      {"dmu/d(c_1)_Ph"             ,   "dmu/d(c_1)_Ph"                                              },
      {"d(mu_0)/d(c_1)_Ph"         ,   "d(mu_0)/d(c_1)_Ph"                                          },
      {"dmu/d(c_2)_Ph"             ,   "dmu/d(c_2)_Ph"                                              },
      {"d(mu_0)/d(c_2)_Ph"         ,   "d(mu_0)/d(c_2)_Ph"                                          },
      {"dmu/d(c_3)_Ph"             ,   "dmu/d(c_3)_Ph"                                              },
      {"d(mu_0)/d(c_3)_Ph"         ,   "d(mu_0)/d(c_3)_Ph"                                          },
      {"dmu/d(c_4)_Ph"             ,   "dmu/d(c_4)_Ph"                                              },
      {"d(mu_0)/d(c_4)_Ph"         ,   "d(mu_0)/d(c_4)_Ph"                                          },
      {"dmu/d(P_0)_h"              ,   "dmu/d(P_0)_h"                                               },
      {"dmu/d(h_0)_P"              ,   "dmu/d(h_0)_P"                                               },
      {"d(mu_0)/dP_h"              ,   "d(mu_0)/dP_h"                                               },
      {"d(mu_0)/dh_P"              ,   "d(mu_0)/dh_P"                                               },
      {"d(mu_0)/d(P_0)_h"          ,   "d(mu_0)/d(P_0)_h"                                           },
      {"d(mu_0)/d(h_0)_P"          ,   "d(mu_0)/d(h_0)_P"                                           },
      {"dlambda/d(c_0)_Ph"         ,   "dlambda/d(c_0)_Ph"                                          },
      {"d(lambda_0)/d(c_0)_Ph"     ,   "d(lambda_0)/d(c_0)_Ph"                                      },
      {"dlambda/d(c_1)_Ph"         ,   "dlambda/d(c_1)_Ph"                                          },
      {"d(lambda_0)/d(c_1)_Ph"     ,   "d(lambda_0)/d(c_1)_Ph"                                      },
      {"dlambda/d(c_2)_Ph"         ,   "dlambda/d(c_2)_Ph"                                          },
      {"d(lambda_0)/d(c_2)_Ph"     ,   "d(lambda_0)/d(c_2)_Ph"                                      },
      {"dlambda/d(c_3)_Ph"         ,   "dlambda/d(c_3)_Ph"                                          },
      {"d(lambda_0)/d(c_3)_Ph"     ,   "d(lambda_0)/d(c_3)_Ph"                                      },
      {"dlambda/d(c_4)_Ph"         ,   "dlambda/d(c_4)_Ph"                                          },
      {"d(lambda_0)/d(c_4)_Ph"     ,   "d(lambda_0)/d(c_4)_Ph"                                      },
      {"dlambda/d(P_0)_h"          ,   "dlambda/d(P_0)_h"                                           },
      {"dlambda/d(h_0)_P"          ,   "dlambda/d(h_0)_P"                                           },
      {"d(lambda_0)/dP_h"          ,   "d(lambda_0)/dP_h"                                           },
      {"d(lambda_0)/dh_P"          ,   "d(lambda_0)/dh_P"                                           },
      {"d(lambda_0)/d(P_0)_h"      ,   "d(lambda_0)/d(P_0)_h"                                       },
      {"d(lambda_0)/d(h_0)_P"      ,   "d(lambda_0)/d(h_0)_P"                                       },
      {"dcp/d(c_0)_Ph"             ,   "dcp/d(c_0)_Ph"                                              },
      {"d(cp_0)/d(c_0)_Ph"         ,   "d(cp_0)/d(c_0)_Ph"                                          },
      {"dcp/d(c_1)_Ph"             ,   "dcp/d(c_1)_Ph"                                              },
      {"d(cp_0)/d(c_1)_Ph"         ,   "d(cp_0)/d(c_1)_Ph"                                          },
      {"dcp/d(c_2)_Ph"             ,   "dcp/d(c_2)_Ph"                                              },
      {"d(cp_0)/d(c_2)_Ph"         ,   "d(cp_0)/d(c_2)_Ph"                                          },
      {"dcp/d(c_3)_Ph"             ,   "dcp/d(c_3)_Ph"                                              },
      {"d(cp_0)/d(c_3)_Ph"         ,   "d(cp_0)/d(c_3)_Ph"                                          },
      {"dcp/d(c_4)_Ph"             ,   "dcp/d(c_4)_Ph"                                              },
      {"d(cp_0)/d(c_4)_Ph"         ,   "d(cp_0)/d(c_4)_Ph"                                          },
      {"dcp/d(P_0)_h"              ,   "dcp/d(P_0)_h"                                               },
      {"dcp/d(h_0)_P"              ,   "dcp/d(h_0)_P"                                               },
      {"d(cp_0)/dP_h"              ,   "d(cp_0)/dP_h"                                               },
      {"d(cp_0)/dh_P"              ,   "d(cp_0)/dh_P"                                               },
      {"d(cp_0)/d(P_0)_h"          ,   "d(cp_0)/d(P_0)_h"                                           },
      {"d(cp_0)/d(h_0)_P"          ,   "d(cp_0)/d(h_0)_P"                                           },
      {"dsigma/d(c_0)_Ph"          ,   "dsigma/d(c_0)_Ph"                                           },
      {"d(sigma_0)/d(c_0)_Ph"      ,   "d(sigma_0)/d(c_0)_Ph"                                       },
      {"dsigma/d(c_1)_Ph"          ,   "dsigma/d(c_1)_Ph"                                           },
      {"d(sigma_0)/d(c_1)_Ph"      ,   "d(sigma_0)/d(c_1)_Ph"                                       },
      {"dsigma/d(c_2)_Ph"          ,   "dsigma/d(c_2)_Ph"                                           },
      {"d(sigma_0)/d(c_2)_Ph"      ,   "d(sigma_0)/d(c_2)_Ph"                                       },
      {"dsigma/d(c_3)_Ph"          ,   "dsigma/d(c_3)_Ph"                                           },
      {"d(sigma_0)/d(c_3)_Ph"      ,   "d(sigma_0)/d(c_3)_Ph"                                       },
      {"dsigma/d(c_4)_Ph"          ,   "dsigma/d(c_4)_Ph"                                           },
      {"d(sigma_0)/d(c_4)_Ph"      ,   "d(sigma_0)/d(c_4)_Ph"                                       },
      {"dsigma/d(P_0)_h"           ,   "dsigma/d(P_0)_h"                                            },
      {"dsigma/d(h_0)_P"           ,   "dsigma/d(h_0)_P"                                            },
      {"d(sigma_0)/dP_h"           ,   "d(sigma_0)/dP_h"                                            },
      {"d(sigma_0)/dh_P"           ,   "d(sigma_0)/dh_P"                                            },
      {"d(sigma_0)/d(P_0)_h"       ,   "d(sigma_0)/d(P_0)_h"                                        },
      {"d(sigma_0)/d(h_0)_P"       ,   "d(sigma_0)/d(h_0)_P"                                        },
      {"dw/d(c_0)_Ph"              ,   "dw/d(c_0)_Ph"                                               },
      {"d(w_0)/d(c_0)_Ph"          ,   "d(w_0)/d(c_0)_Ph"                                           },
      {"dw/d(c_1)_Ph"              ,   "dw/d(c_1)_Ph"                                               },
      {"d(w_0)/d(c_1)_Ph"          ,   "d(w_0)/d(c_1)_Ph"                                           },
      {"dw/d(c_2)_Ph"              ,   "dw/d(c_2)_Ph"                                               },
      {"d(w_0)/d(c_2)_Ph"          ,   "d(w_0)/d(c_2)_Ph"                                           },
      {"dw/d(c_3)_Ph"              ,   "dw/d(c_3)_Ph"                                               },
      {"d(w_0)/d(c_3)_Ph"          ,   "d(w_0)/d(c_3)_Ph"                                           },
      {"dw/d(c_4)_Ph"              ,   "dw/d(c_4)_Ph"                                               },
      {"d(w_0)/d(c_4)_Ph"          ,   "d(w_0)/d(c_4)_Ph"                                           },
      {"dw/d(P_0)_h"               ,   "dw/d(P_0)_h"                                                },
      {"dw/d(h_0)_P"               ,   "dw/d(h_0)_P"                                                },
      {"d(w_0)/dP_h"               ,   "d(w_0)/dP_h"                                                },
      {"d(w_0)/dh_P"               ,   "d(w_0)/dh_P"                                                },
      {"d(w_0)/d(P_0)_h"           ,   "d(w_0)/d(P_0)_h"                                            },
      {"d(w_0)/d(h_0)_P"           ,   "d(w_0)/d(h_0)_P"                                            },
      {"dg/d(c_0)_Ph"              ,   "dg/d(c_0)_Ph"                                               },
      {"d(g_0)/d(c_0)_Ph"          ,   "d(g_0)/d(c_0)_Ph"                                           },
      {"dg/d(c_1)_Ph"              ,   "dg/d(c_1)_Ph"                                               },
      {"d(g_0)/d(c_1)_Ph"          ,   "d(g_0)/d(c_1)_Ph"                                           },
      {"dg/d(c_2)_Ph"              ,   "dg/d(c_2)_Ph"                                               },
      {"d(g_0)/d(c_2)_Ph"          ,   "d(g_0)/d(c_2)_Ph"                                           },
      {"dg/d(c_3)_Ph"              ,   "dg/d(c_3)_Ph"                                               },
      {"d(g_0)/d(c_3)_Ph"          ,   "d(g_0)/d(c_3)_Ph"                                           },
      {"dg/d(c_4)_Ph"              ,   "dg/d(c_4)_Ph"                                               },
      {"d(g_0)/d(c_4)_Ph"          ,   "d(g_0)/d(c_4)_Ph"                                           },
      {"dg/d(P_0)_h"               ,   "dg/d(P_0)_h"                                                },
      {"dg/d(h_0)_P"               ,   "dg/d(h_0)_P"                                                },
      {"d(g_0)/dP_h"               ,   "d(g_0)/dP_h"                                                },
      {"d(g_0)/dh_P"               ,   "d(g_0)/dh_P"                                                },
      {"d(g_0)/d(P_0)_h"           ,   "d(g_0)/d(P_0)_h"                                            },
      {"d(g_0)/d(h_0)_P"           ,   "d(g_0)/d(h_0)_P"                                            },
      {"df/d(c_0)_Ph"              ,   "df/d(c_0)_Ph"                                               },
      {"d(f_0)/d(c_0)_Ph"          ,   "d(f_0)/d(c_0)_Ph"                                           },
      {"df/d(c_1)_Ph"              ,   "df/d(c_1)_Ph"                                               },
      {"d(f_0)/d(c_1)_Ph"          ,   "d(f_0)/d(c_1)_Ph"                                           },
      {"df/d(c_2)_Ph"              ,   "df/d(c_2)_Ph"                                               },
      {"d(f_0)/d(c_2)_Ph"          ,   "d(f_0)/d(c_2)_Ph"                                           },
      {"df/d(c_3)_Ph"              ,   "df/d(c_3)_Ph"                                               },
      {"d(f_0)/d(c_3)_Ph"          ,   "d(f_0)/d(c_3)_Ph"                                           },
      {"df/d(c_4)_Ph"              ,   "df/d(c_4)_Ph"                                               },
      {"d(f_0)/d(c_4)_Ph"          ,   "d(f_0)/d(c_4)_Ph"                                           },
      {"df/d(P_0)_h"               ,   "df/d(P_0)_h"                                                },
      {"df/d(h_0)_P"               ,   "df/d(h_0)_P"                                                },
      {"d(f_0)/dP_h"               ,   "d(f_0)/dP_h"                                                },
      {"d(f_0)/dh_P"               ,   "d(f_0)/dh_P"                                                },
      {"d(f_0)/d(P_0)_h"           ,   "d(f_0)/d(P_0)_h"                                            },
      {"d(f_0)/d(h_0)_P"           ,   "d(f_0)/d(h_0)_P"                                            },
      {"dPr/d(c_0)_Ph"             ,   "dPr/d(c_0)_Ph"                                              },
      {"d(Pr_0)/d(c_0)_Ph"         ,   "d(Pr_0)/d(c_0)_Ph"                                          },
      {"dPr/d(c_1)_Ph"             ,   "dPr/d(c_1)_Ph"                                              },
      {"d(Pr_0)/d(c_1)_Ph"         ,   "d(Pr_0)/d(c_1)_Ph"                                          },
      {"dPr/d(c_2)_Ph"             ,   "dPr/d(c_2)_Ph"                                              },
      {"d(Pr_0)/d(c_2)_Ph"         ,   "d(Pr_0)/d(c_2)_Ph"                                          },
      {"dPr/d(c_3)_Ph"             ,   "dPr/d(c_3)_Ph"                                              },
      {"d(Pr_0)/d(c_3)_Ph"         ,   "d(Pr_0)/d(c_3)_Ph"                                          },
      {"dPr/d(c_4)_Ph"             ,   "dPr/d(c_4)_Ph"                                              },
      {"d(Pr_0)/d(c_4)_Ph"         ,   "d(Pr_0)/d(c_4)_Ph"                                          },
      {"dPr/d(P_0)_h"              ,   "dPr/d(P_0)_h"                                               },
      {"dPr/d(h_0)_P"              ,   "dPr/d(h_0)_P"                                               },
      {"d(Pr_0)/dP_h"              ,   "d(Pr_0)/dP_h"                                               },
      {"d(Pr_0)/dh_P"              ,   "d(Pr_0)/dh_P"                                               },
      {"d(Pr_0)/d(P_0)_h"          ,   "d(Pr_0)/d(P_0)_h"                                           },
      {"d(Pr_0)/d(h_0)_P"          ,   "d(Pr_0)/d(h_0)_P"                                           },
      {"dbeta/d(c_0)_Ph"           ,   "dbeta/d(c_0)_Ph"                                            },
      {"d(beta_0)/d(c_0)_Ph"       ,   "d(beta_0)/d(c_0)_Ph"                                        },
      {"dbeta/d(c_1)_Ph"           ,   "dbeta/d(c_1)_Ph"                                            },
      {"d(beta_0)/d(c_1)_Ph"       ,   "d(beta_0)/d(c_1)_Ph"                                        },
      {"dbeta/d(c_2)_Ph"           ,   "dbeta/d(c_2)_Ph"                                            },
      {"d(beta_0)/d(c_2)_Ph"       ,   "d(beta_0)/d(c_2)_Ph"                                        },
      {"dbeta/d(c_3)_Ph"           ,   "dbeta/d(c_3)_Ph"                                            },
      {"d(beta_0)/d(c_3)_Ph"       ,   "d(beta_0)/d(c_3)_Ph"                                        },
      {"dbeta/d(c_4)_Ph"           ,   "dbeta/d(c_4)_Ph"                                            },
      {"d(beta_0)/d(c_4)_Ph"       ,   "d(beta_0)/d(c_4)_Ph"                                        },
      {"dbeta/d(P_0)_h"            ,   "dbeta/d(P_0)_h"                                             },
      {"dbeta/d(h_0)_P"            ,   "dbeta/d(h_0)_P"                                             },
      {"d(beta_0)/dP_h"            ,   "d(beta_0)/dP_h"                                             },
      {"d(beta_0)/dh_P"            ,   "d(beta_0)/dh_P"                                             },
      {"d(beta_0)/d(P_0)_h"        ,   "d(beta_0)/d(P_0)_h"                                         },
      {"d(beta_0)/d(h_0)_P"        ,   "d(beta_0)/d(h_0)_P"                                         },
      {"dgamma/d(c_0)_Ph"          ,   "dgamma/d(c_0)_Ph"                                           },
      {"d(gamma_0)/d(c_0)_Ph"      ,   "d(gamma_0)/d(c_0)_Ph"                                       },
      {"dgamma/d(c_1)_Ph"          ,   "dgamma/d(c_1)_Ph"                                           },
      {"d(gamma_0)/d(c_1)_Ph"      ,   "d(gamma_0)/d(c_1)_Ph"                                       },
      {"dgamma/d(c_2)_Ph"          ,   "dgamma/d(c_2)_Ph"                                           },
      {"d(gamma_0)/d(c_2)_Ph"      ,   "d(gamma_0)/d(c_2)_Ph"                                       },
      {"dgamma/d(c_3)_Ph"          ,   "dgamma/d(c_3)_Ph"                                           },
      {"d(gamma_0)/d(c_3)_Ph"      ,   "d(gamma_0)/d(c_3)_Ph"                                       },
      {"dgamma/d(c_4)_Ph"          ,   "dgamma/d(c_4)_Ph"                                           },
      {"d(gamma_0)/d(c_4)_Ph"      ,   "d(gamma_0)/d(c_4)_Ph"                                       },
      {"dgamma/d(P_0)_h"           ,   "dgamma/d(P_0)_h"                                            },
      {"dgamma/d(h_0)_P"           ,   "dgamma/d(h_0)_P"                                            },
      {"d(gamma_0)/dP_h"           ,   "d(gamma_0)/dP_h"                                            },
      {"d(gamma_0)/dh_P"           ,   "d(gamma_0)/dh_P"                                            },
      {"d(gamma_0)/d(P_0)_h"       ,   "d(gamma_0)/d(P_0)_h"                                        },
      {"d(gamma_0)/d(h_0)_P"       ,   "d(gamma_0)/d(h_0)_P"                                        },
      {"d(rho_lsat)/d(c_0)_Ph"     ,   "d(rho_lsat)/d(c_0)_Ph"                                      },
      {"d(rho_lsat_0)/d(c_0)_Ph"   ,   "d(rho_lsat_0)/d(c_0)_Ph"                                    },
      {"d(rho_lsat)/d(c_1)_Ph"     ,   "d(rho_lsat)/d(c_1)_Ph"                                      },
      {"d(rho_lsat_0)/d(c_1)_Ph"   ,   "d(rho_lsat_0)/d(c_1)_Ph"                                    },
      {"d(rho_lsat)/d(c_2)_Ph"     ,   "d(rho_lsat)/d(c_2)_Ph"                                      },
      {"d(rho_lsat_0)/d(c_2)_Ph"   ,   "d(rho_lsat_0)/d(c_2)_Ph"                                    },
      {"d(rho_lsat)/d(c_3)_Ph"     ,   "d(rho_lsat)/d(c_3)_Ph"                                      },
      {"d(rho_lsat_0)/d(c_3)_Ph"   ,   "d(rho_lsat_0)/d(c_3)_Ph"                                    },
      {"d(rho_lsat)/d(c_4)_Ph"     ,   "d(rho_lsat)/d(c_4)_Ph"                                      },
      {"d(rho_lsat_0)/d(c_4)_Ph"   ,   "d(rho_lsat_0)/d(c_4)_Ph"                                    },
      {"d(rho_lsat)/d(P_0)_h"      ,   "d(rho_lsat)/d(P_0)_h"                                       },
      {"d(rho_lsat)/d(h_0)_P"      ,   "d(rho_lsat)/d(h_0)_P"                                       },
      {"d(rho_lsat_0)/dP_h"        ,   "d(rho_lsat_0)/dP_h"                                         },
      {"d(rho_lsat_0)/dh_P"        ,   "d(rho_lsat_0)/dh_P"                                         },
      {"d(rho_lsat_0)/d(P_0)_h"    ,   "d(rho_lsat_0)/d(P_0)_h"                                     },
      {"d(rho_lsat_0)/d(h_0)_P"    ,   "d(rho_lsat_0)/d(h_0)_P"                                     },
      {"d(rho_vsat)/d(c_0)_Ph"     ,   "d(rho_vsat)/d(c_0)_Ph"                                      },
      {"d(rho_vsat_0)/d(c_0)_Ph"   ,   "d(rho_vsat_0)/d(c_0)_Ph"                                    },
      {"d(rho_vsat)/d(c_1)_Ph"     ,   "d(rho_vsat)/d(c_1)_Ph"                                      },
      {"d(rho_vsat_0)/d(c_1)_Ph"   ,   "d(rho_vsat_0)/d(c_1)_Ph"                                    },
      {"d(rho_vsat)/d(c_2)_Ph"     ,   "d(rho_vsat)/d(c_2)_Ph"                                      },
      {"d(rho_vsat_0)/d(c_2)_Ph"   ,   "d(rho_vsat_0)/d(c_2)_Ph"                                    },
      {"d(rho_vsat)/d(c_3)_Ph"     ,   "d(rho_vsat)/d(c_3)_Ph"                                      },
      {"d(rho_vsat_0)/d(c_3)_Ph"   ,   "d(rho_vsat_0)/d(c_3)_Ph"                                    },
      {"d(rho_vsat)/d(c_4)_Ph"     ,   "d(rho_vsat)/d(c_4)_Ph"                                      },
      {"d(rho_vsat_0)/d(c_4)_Ph"   ,   "d(rho_vsat_0)/d(c_4)_Ph"                                    },
      {"d(rho_vsat)/d(P_0)_h"      ,   "d(rho_vsat)/d(P_0)_h"                                       },
      {"d(rho_vsat)/d(h_0)_P"      ,   "d(rho_vsat)/d(h_0)_P"                                       },
      {"d(rho_vsat_0)/dP_h"        ,   "d(rho_vsat_0)/dP_h"                                         },
      {"d(rho_vsat_0)/dh_P"        ,   "d(rho_vsat_0)/dh_P"                                         },
      {"d(rho_vsat_0)/d(P_0)_h"    ,   "d(rho_vsat_0)/d(P_0)_h"                                     },
      {"d(rho_vsat_0)/d(h_0)_P"    ,   "d(rho_vsat_0)/d(h_0)_P"                                     },
      {"d(h_lsat)/d(c_0)_Ph"       ,   "d(h_lsat)/d(c_0)_Ph"                                        },
      {"d(h_lsat_0)/d(c_0)_Ph"     ,   "d(h_lsat_0)/d(c_0)_Ph"                                      },
      {"d(h_lsat)/d(c_1)_Ph"       ,   "d(h_lsat)/d(c_1)_Ph"                                        },
      {"d(h_lsat_0)/d(c_1)_Ph"     ,   "d(h_lsat_0)/d(c_1)_Ph"                                      },
      {"d(h_lsat)/d(c_2)_Ph"       ,   "d(h_lsat)/d(c_2)_Ph"                                        },
      {"d(h_lsat_0)/d(c_2)_Ph"     ,   "d(h_lsat_0)/d(c_2)_Ph"                                      },
      {"d(h_lsat)/d(c_3)_Ph"       ,   "d(h_lsat)/d(c_3)_Ph"                                        },
      {"d(h_lsat_0)/d(c_3)_Ph"     ,   "d(h_lsat_0)/d(c_3)_Ph"                                      },
      {"d(h_lsat)/d(c_4)_Ph"       ,   "d(h_lsat)/d(c_4)_Ph"                                        },
      {"d(h_lsat_0)/d(c_4)_Ph"     ,   "d(h_lsat_0)/d(c_4)_Ph"                                      },
      {"d(h_lsat)/d(P_0)_h"        ,   "d(h_lsat)/d(P_0)_h"                                         },
      {"d(h_lsat)/d(h_0)_P"        ,   "d(h_lsat)/d(h_0)_P"                                         },
      {"d(h_lsat_0)/dP_h"          ,   "d(h_lsat_0)/dP_h"                                           },
      {"d(h_lsat_0)/dh_P"          ,   "d(h_lsat_0)/dh_P"                                           },
      {"d(h_lsat_0)/d(P_0)_h"      ,   "d(h_lsat_0)/d(P_0)_h"                                       },
      {"d(h_lsat_0)/d(h_0)_P"      ,   "d(h_lsat_0)/d(h_0)_P"                                       },
      {"d(h_vsat)/d(c_0)_Ph"       ,   "d(h_vsat)/d(c_0)_Ph"                                        },
      {"d(h_vsat_0)/d(c_0)_Ph"     ,   "d(h_vsat_0)/d(c_0)_Ph"                                      },
      {"d(h_vsat)/d(c_1)_Ph"       ,   "d(h_vsat)/d(c_1)_Ph"                                        },
      {"d(h_vsat_0)/d(c_1)_Ph"     ,   "d(h_vsat_0)/d(c_1)_Ph"                                      },
      {"d(h_vsat)/d(c_2)_Ph"       ,   "d(h_vsat)/d(c_2)_Ph"                                        },
      {"d(h_vsat_0)/d(c_2)_Ph"     ,   "d(h_vsat_0)/d(c_2)_Ph"                                      },
      {"d(h_vsat)/d(c_3)_Ph"       ,   "d(h_vsat)/d(c_3)_Ph"                                        },
      {"d(h_vsat_0)/d(c_3)_Ph"     ,   "d(h_vsat_0)/d(c_3)_Ph"                                      },
      {"d(h_vsat)/d(c_4)_Ph"       ,   "d(h_vsat)/d(c_4)_Ph"                                        },
      {"d(h_vsat_0)/d(c_4)_Ph"     ,   "d(h_vsat_0)/d(c_4)_Ph"                                      },
      {"d(h_vsat)/d(P_0)_h"        ,   "d(h_vsat)/d(P_0)_h"                                         },
      {"d(h_vsat)/d(h_0)_P"        ,   "d(h_vsat)/d(h_0)_P"                                         },
      {"d(h_vsat_0)/dP_h"          ,   "d(h_vsat_0)/dP_h"                                           },
      {"d(h_vsat_0)/dh_P"          ,   "d(h_vsat_0)/dh_P"                                           },
      {"d(h_vsat_0)/d(P_0)_h"      ,   "d(h_vsat_0)/d(P_0)_h"                                       },
      {"d(h_vsat_0)/d(h_0)_P"      ,   "d(h_vsat_0)/d(h_0)_P"                                       },
      {"d(cp_lsat)/d(c_0)_Ph"      ,   "d(cp_lsat)/d(c_0)_Ph"                                       },
      {"d(cp_lsat_0)/d(c_0)_Ph"    ,   "d(cp_lsat_0)/d(c_0)_Ph"                                     },
      {"d(cp_lsat)/d(c_1)_Ph"      ,   "d(cp_lsat)/d(c_1)_Ph"                                       },
      {"d(cp_lsat_0)/d(c_1)_Ph"    ,   "d(cp_lsat_0)/d(c_1)_Ph"                                     },
      {"d(cp_lsat)/d(c_2)_Ph"      ,   "d(cp_lsat)/d(c_2)_Ph"                                       },
      {"d(cp_lsat_0)/d(c_2)_Ph"    ,   "d(cp_lsat_0)/d(c_2)_Ph"                                     },
      {"d(cp_lsat)/d(c_3)_Ph"      ,   "d(cp_lsat)/d(c_3)_Ph"                                       },
      {"d(cp_lsat_0)/d(c_3)_Ph"    ,   "d(cp_lsat_0)/d(c_3)_Ph"                                     },
      {"d(cp_lsat)/d(c_4)_Ph"      ,   "d(cp_lsat)/d(c_4)_Ph"                                       },
      {"d(cp_lsat_0)/d(c_4)_Ph"    ,   "d(cp_lsat_0)/d(c_4)_Ph"                                     },
      {"d(cp_lsat)/d(P_0)_h"       ,   "d(cp_lsat)/d(P_0)_h"                                        },
      {"d(cp_lsat)/d(h_0)_P"       ,   "d(cp_lsat)/d(h_0)_P"                                        },
      {"d(cp_lsat_0)/dP_h"         ,   "d(cp_lsat_0)/dP_h"                                          },
      {"d(cp_lsat_0)/dh_P"         ,   "d(cp_lsat_0)/dh_P"                                          },
      {"d(cp_lsat_0)/d(P_0)_h"     ,   "d(cp_lsat_0)/d(P_0)_h"                                      },
      {"d(cp_lsat_0)/d(h_0)_P"     ,   "d(cp_lsat_0)/d(h_0)_P"                                      },
      {"d(cp_vsat)/d(c_0)_Ph"      ,   "d(cp_vsat)/d(c_0)_Ph"                                       },
      {"d(cp_vsat_0)/d(c_0)_Ph"    ,   "d(cp_vsat_0)/d(c_0)_Ph"                                     },
      {"d(cp_vsat)/d(c_1)_Ph"      ,   "d(cp_vsat)/d(c_1)_Ph"                                       },
      {"d(cp_vsat_0)/d(c_1)_Ph"    ,   "d(cp_vsat_0)/d(c_1)_Ph"                                     },
      {"d(cp_vsat)/d(c_2)_Ph"      ,   "d(cp_vsat)/d(c_2)_Ph"                                       },
      {"d(cp_vsat_0)/d(c_2)_Ph"    ,   "d(cp_vsat_0)/d(c_2)_Ph"                                     },
      {"d(cp_vsat)/d(c_3)_Ph"      ,   "d(cp_vsat)/d(c_3)_Ph"                                       },
      {"d(cp_vsat_0)/d(c_3)_Ph"    ,   "d(cp_vsat_0)/d(c_3)_Ph"                                     },
      {"d(cp_vsat)/d(c_4)_Ph"      ,   "d(cp_vsat)/d(c_4)_Ph"                                       },
      {"d(cp_vsat_0)/d(c_4)_Ph"    ,   "d(cp_vsat_0)/d(c_4)_Ph"                                     },
      {"d(cp_vsat)/d(P_0)_h"       ,   "d(cp_vsat)/d(P_0)_h"                                        },
      {"d(cp_vsat)/d(h_0)_P"       ,   "d(cp_vsat)/d(h_0)_P"                                        },
      {"d(cp_vsat_0)/dP_h"         ,   "d(cp_vsat_0)/dP_h"                                          },
      {"d(cp_vsat_0)/dh_P"         ,   "d(cp_vsat_0)/dh_P"                                          },
      {"d(cp_vsat_0)/d(P_0)_h"     ,   "d(cp_vsat_0)/d(P_0)_h"                                      },
      {"d(cp_vsat_0)/d(h_0)_P"     ,   "d(cp_vsat_0)/d(h_0)_P"                                      },
      {"d(T_sat)/d(c_0)_Ph"        ,   "d(T_sat)/d(c_0)_Ph"                                         },
      {"d(T_sat_0)/d(c_0)_Ph"      ,   "d(T_sat_0)/d(c_0)_Ph"                                       },
      {"d(T_sat)/d(c_1)_Ph"        ,   "d(T_sat)/d(c_1)_Ph"                                         },
      {"d(T_sat_0)/d(c_1)_Ph"      ,   "d(T_sat_0)/d(c_1)_Ph"                                       },
      {"d(T_sat)/d(c_2)_Ph"        ,   "d(T_sat)/d(c_2)_Ph"                                         },
      {"d(T_sat_0)/d(c_2)_Ph"      ,   "d(T_sat_0)/d(c_2)_Ph"                                       },
      {"d(T_sat)/d(c_3)_Ph"        ,   "d(T_sat)/d(c_3)_Ph"                                         },
      {"d(T_sat_0)/d(c_3)_Ph"      ,   "d(T_sat_0)/d(c_3)_Ph"                                       },
      {"d(T_sat)/d(c_4)_Ph"        ,   "d(T_sat)/d(c_4)_Ph"                                         },
      {"d(T_sat_0)/d(c_4)_Ph"      ,   "d(T_sat_0)/d(c_4)_Ph"                                       },
      {"d(T_sat)/d(P_0)_h"         ,   "d(T_sat)/d(P_0)_h"                                          },
      {"d(T_sat)/d(h_0)_P"         ,   "d(T_sat)/d(h_0)_P"                                          },
      {"d(T_sat_0)/dP_h"           ,   "d(T_sat_0)/dP_h"                                            },
      {"d(T_sat_0)/dh_P"           ,   "d(T_sat_0)/dh_P"                                            },
      {"d(T_sat_0)/d(P_0)_h"       ,   "d(T_sat_0)/d(P_0)_h"                                        },
      {"d(T_sat_0)/d(h_0)_P"       ,   "d(T_sat_0)/d(h_0)_P"                                        },
      {"d(P_0)/dP_h"               ,   "d(P_0)/dP_h"                                                },
      {"d(P_0)/dh_P"               ,   "d(P_0)/dh_P"                                                },
      {"d(P_0)/d(c_0)_Ph"          ,   "d(P_0)/d(c_0)_Ph"                                           },
      {"d(P_0)/d(c_1)_Ph"          ,   "d(P_0)/d(c_1)_Ph"                                           },
      {"d(P_0)/d(c_2)_Ph"          ,   "d(P_0)/d(c_2)_Ph"                                           },
      {"d(P_0)/d(c_3)_Ph"          ,   "d(P_0)/d(c_3)_Ph"                                           },
      {"d(P_0)/d(c_4)_Ph"          ,   "d(P_0)/d(c_4)_Ph"                                           },
      {"d(h_0)/dP_h"               ,   "d(h_0)/dP_h"                                                },
      {"d(h_0)/dh_P"               ,   "d(h_0)/dh_P"                                                },
      {"d(h_0)/d(c_0)_Ph"          ,   "d(h_0)/d(c_0)_Ph"                                           },
      {"d(h_0)/d(c_1)_Ph"          ,   "d(h_0)/d(c_1)_Ph"                                           },
      {"d(h_0)/d(c_2)_Ph"          ,   "d(h_0)/d(c_2)_Ph"                                           },
      {"d(h_0)/d(c_3)_Ph"          ,   "d(h_0)/d(c_3)_Ph"                                           },
      {"d(h_0)/d(c_4)_Ph"          ,   "d(h_0)/d(c_4)_Ph"                                           },
      {"dh/d(c_1)_PT"              ,   "dh/d(c_1)_PT"                                               },
      {"dh/d(c_2)_PT"              ,   "dh/d(c_2)_PT"                                               },
      {"dh/d(c_3)_PT"              ,   "dh/d(c_3)_PT"                                               },
      {"dh/d(c_4)_PT"              ,   "dh/d(c_4)_PT"                                               },
      {"ddncv/dP_h"                ,   "ddncv/dP_h"                                                 },
      {"ddncv/dh_P"                ,   "ddncv/dh_P"                                                 },
      {"drnc/d(c_0)_Ph"            ,   "drnc/d(c_0)_Ph"                                             },
      {"drnc/d(c_1)_Ph"            ,   "drnc/d(c_1)_Ph"                                             },
      {"drnc/d(c_2)_Ph"            ,   "drnc/d(c_2)_Ph"                                             },
      {"drnc/d(c_3)_Ph"            ,   "drnc/d(c_3)_Ph"                                             },
      {"drnc/d(c_4)_Ph"            ,   "drnc/d(c_4)_Ph"                                             },
      {"dmnc/d(c_0)_Ph"            ,   "dmnc/d(c_0)_Ph"                                             },
      {"dmnc/d(c_1)_Ph"            ,   "dmnc/d(c_1)_Ph"                                             },
      {"dmnc/d(c_2)_Ph"            ,   "dmnc/d(c_2)_Ph"                                             },
      {"dmnc/d(c_3)_Ph"            ,   "dmnc/d(c_3)_Ph"                                             },
      {"dmnc/d(c_4)_Ph"            ,   "dmnc/d(c_4)_Ph"                                             },
      {"ddncv/d(c_0)_Ph"           ,   "ddncv/d(c_0)_Ph"                                            },
      {"ddncv/d(c_1)_Ph"           ,   "ddncv/d(c_1)_Ph"                                            },
      {"ddncv/d(c_2)_Ph"           ,   "ddncv/d(c_2)_Ph"                                            },
      {"ddncv/d(c_3)_Ph"           ,   "ddncv/d(c_3)_Ph"                                            },
      {"ddncv/d(c_4)_Ph"           ,   "ddncv/d(c_4)_Ph"                                            },
      {"d(mu_0)/d_T_P"             ,   "d(mu_0)/d_T_P"                                              },
      {"d(lambda_0)/d_T_P"         ,   "d(lambda_0)/d_T_P"                                          },

      {"d2(T_sat_0)/d(P_0)d(P_0)"  ,   "d2(T_sat_0)/d(P_0)d(P_0)"                                   }
    };
#if  __cplusplus <  201103L
 static std::vector<typrop> camixprop(t_camixprop, 
                                      t_camixprop + sizeof(t_camixprop) / sizeof(typrop) );
#endif


  enum EOS_camixprop
    { NotACamixProperty = lastLimProperty +1 ,

      c_0         ,
      firstCamixProperty = c_0,
      c_1         ,
      c_2         ,
      c_3         ,
      c_4         ,
      p_0         ,
      p_1         ,
      p_2         ,
      p_3         ,
      p_4         ,
      h_0         ,
      h_1         ,
      h_2         ,
      h_3         ,
      h_4         ,
      T_0         ,
      rho_0       ,
      u_0         ,
      s_0         ,
      mu_0        ,
      lambda_0    ,
      cp_0        ,
      sigma_0     ,
      w_0         ,
      g_0         ,
      f_0         ,
      pr_0        ,
      beta_0      ,
      gamma_0     ,
      T_sat_0     ,
      rho_l_sat_0 ,
      rho_v_sat_0 ,
      h_l_sat_0   ,
      h_v_sat_0   ,
      cp_l_sat_0  ,
      cp_v_sat_0  ,
      dncv        ,
      rnc         ,
      mnc         ,
      xnc         ,
      xvap        ,
      prgr        ,

      d_T_d_c_0_ph           = prgr + 2 ,
      d_T_0_d_c_0_ph         ,
      d_T_d_c_1_ph           ,
      d_T_0_d_c_1_ph         ,
      d_T_d_c_2_ph           ,
      d_T_0_d_c_2_ph         ,
      d_T_d_c_3_ph           ,
      d_T_0_d_c_3_ph         ,
      d_T_d_c_4_ph           ,
      d_T_0_d_c_4_ph         ,
      d_T_d_p_0_h            ,
      d_T_d_h_0_p            ,
      d_T_0_d_p_h            ,
      d_T_0_d_h_p            ,
      d_T_0_d_p_0_h          ,
      d_T_0_d_h_0_p          ,
      d_rho_d_c_0_ph         ,
      d_rho_0_d_c_0_ph       ,
      d_rho_d_c_1_ph         ,
      d_rho_0_d_c_1_ph       ,
      d_rho_d_c_2_ph         ,
      d_rho_0_d_c_2_ph       ,
      d_rho_d_c_3_ph         ,
      d_rho_0_d_c_3_ph       ,
      d_rho_d_c_4_ph         ,
      d_rho_0_d_c_4_ph       ,
      d_rho_d_p_0_h          ,
      d_rho_d_h_0_p          ,
      d_rho_0_d_p_h          ,
      d_rho_0_d_h_p          ,
      d_rho_0_d_p_0_h        ,
      d_rho_0_d_h_0_p        ,
      d_u_d_c_0_ph           ,
      d_u_0_d_c_0_ph         ,
      d_u_d_c_1_ph           ,
      d_u_0_d_c_1_ph         ,
      d_u_d_c_2_ph           ,
      d_u_0_d_c_2_ph         ,
      d_u_d_c_3_ph           ,
      d_u_0_d_c_3_ph         ,
      d_u_d_c_4_ph           ,
      d_u_0_d_c_4_ph         ,
      d_u_d_p_0_h            ,
      d_u_d_h_0_p            ,
      d_u_0_d_p_h            ,
      d_u_0_d_h_p            ,
      d_u_0_d_p_0_h          ,
      d_u_0_d_h_0_p          ,
      d_s_d_c_0_ph           ,
      d_s_0_d_c_0_ph         ,
      d_s_d_c_1_ph           ,
      d_s_0_d_c_1_ph         ,
      d_s_d_c_2_ph           ,
      d_s_0_d_c_2_ph         ,
      d_s_d_c_3_ph           ,
      d_s_0_d_c_3_ph         ,
      d_s_d_c_4_ph           ,
      d_s_0_d_c_4_ph         ,
      d_s_d_p_0_h            ,
      d_s_d_h_0_p            ,
      d_s_0_d_p_h            ,
      d_s_0_d_h_p            ,
      d_s_0_d_p_0_h          ,
      d_s_0_d_h_0_p          ,
      d_mu_d_c_0_ph          ,
      d_mu_0_d_c_0_ph        ,
      d_mu_d_c_1_ph          ,
      d_mu_0_d_c_1_ph        ,
      d_mu_d_c_2_ph          ,
      d_mu_0_d_c_2_ph        ,
      d_mu_d_c_3_ph          ,
      d_mu_0_d_c_3_ph        ,
      d_mu_d_c_4_ph          ,
      d_mu_0_d_c_4_ph        ,
      d_mu_d_p_0_h           ,
      d_mu_d_h_0_p           ,
      d_mu_0_d_p_h           ,
      d_mu_0_d_h_p           ,
      d_mu_0_d_p_0_h         ,
      d_mu_0_d_h_0_p         ,
      d_lambda_d_c_0_ph      ,
      d_lambda_0_d_c_0_ph    ,
      d_lambda_d_c_1_ph      ,
      d_lambda_0_d_c_1_ph    ,
      d_lambda_d_c_2_ph      ,
      d_lambda_0_d_c_2_ph    ,
      d_lambda_d_c_3_ph      ,
      d_lambda_0_d_c_3_ph    ,
      d_lambda_d_c_4_ph      ,
      d_lambda_0_d_c_4_ph    ,
      d_lambda_d_p_0_h       ,
      d_lambda_d_h_0_p       ,
      d_lambda_0_d_p_h       ,
      d_lambda_0_d_h_p       ,
      d_lambda_0_d_p_0_h     ,
      d_lambda_0_d_h_0_p     ,
      d_cp_d_c_0_ph          ,
      d_cp_0_d_c_0_ph        ,
      d_cp_d_c_1_ph          ,
      d_cp_0_d_c_1_ph        ,
      d_cp_d_c_2_ph          ,
      d_cp_0_d_c_2_ph        ,
      d_cp_d_c_3_ph          ,
      d_cp_0_d_c_3_ph        ,
      d_cp_d_c_4_ph          ,
      d_cp_0_d_c_4_ph        ,
      d_cp_d_p_0_h           ,
      d_cp_d_h_0_p           ,
      d_cp_0_d_p_h           ,
      d_cp_0_d_h_p           ,
      d_cp_0_d_p_0_h         ,
      d_cp_0_d_h_0_p         ,
      d_sigma_d_c_0_ph       ,
      d_sigma_0_d_c_0_ph     ,
      d_sigma_d_c_1_ph       ,
      d_sigma_0_d_c_1_ph     ,
      d_sigma_d_c_2_ph       ,
      d_sigma_0_d_c_2_ph     ,
      d_sigma_d_c_3_ph       ,
      d_sigma_0_d_c_3_ph     ,
      d_sigma_d_c_4_ph       ,
      d_sigma_0_d_c_4_ph     ,
      d_sigma_d_p_0_h        ,
      d_sigma_d_h_0_p        ,
      d_sigma_0_d_p_h        ,
      d_sigma_0_d_h_p        ,
      d_sigma_0_d_p_0_h      ,
      d_sigma_0_d_h_0_p      ,
      d_w_d_c_0_ph           ,
      d_w_0_d_c_0_ph         ,
      d_w_d_c_1_ph           ,
      d_w_0_d_c_1_ph         ,
      d_w_d_c_2_ph           ,
      d_w_0_d_c_2_ph         ,
      d_w_d_c_3_ph           ,
      d_w_0_d_c_3_ph         ,
      d_w_d_c_4_ph           ,
      d_w_0_d_c_4_ph         ,
      d_w_d_p_0_h            ,
      d_w_d_h_0_p            ,
      d_w_0_d_p_h            ,
      d_w_0_d_h_p            ,
      d_w_0_d_p_0_h          ,
      d_w_0_d_h_0_p          ,
      d_g_d_c_0_ph           ,
      d_g_0_d_c_0_ph         ,
      d_g_d_c_1_ph           ,
      d_g_0_d_c_1_ph         ,
      d_g_d_c_2_ph           ,
      d_g_0_d_c_2_ph         ,
      d_g_d_c_3_ph           ,
      d_g_0_d_c_3_ph         ,
      d_g_d_c_4_ph           ,
      d_g_0_d_c_4_ph         ,
      d_g_d_p_0_h            ,
      d_g_d_h_0_p            ,
      d_g_0_d_p_h            ,
      d_g_0_d_h_p            ,
      d_g_0_d_p_0_h          ,
      d_g_0_d_h_0_p          ,
      d_f_d_c_0_ph           ,
      d_f_0_d_c_0_ph         ,
      d_f_d_c_1_ph           ,
      d_f_0_d_c_1_ph         ,
      d_f_d_c_2_ph           ,
      d_f_0_d_c_2_ph         ,
      d_f_d_c_3_ph           ,
      d_f_0_d_c_3_ph         ,
      d_f_d_c_4_ph           ,
      d_f_0_d_c_4_ph         ,
      d_f_d_p_0_h            ,
      d_f_d_h_0_p            ,
      d_f_0_d_p_h            ,
      d_f_0_d_h_p            ,
      d_f_0_d_p_0_h          ,
      d_f_0_d_h_0_p          ,
      d_pr_d_c_0_ph          ,
      d_pr_0_d_c_0_ph        ,
      d_pr_d_c_1_ph          ,
      d_pr_0_d_c_1_ph        ,
      d_pr_d_c_2_ph          ,
      d_pr_0_d_c_2_ph        ,
      d_pr_d_c_3_ph          ,
      d_pr_0_d_c_3_ph        ,
      d_pr_d_c_4_ph          ,
      d_pr_0_d_c_4_ph        ,
      d_pr_d_p_0_h           ,
      d_pr_d_h_0_p           ,
      d_pr_0_d_p_h           ,
      d_pr_0_d_h_p           ,
      d_pr_0_d_p_0_h         ,
      d_pr_0_d_h_0_p         ,
      d_beta_d_c_0_ph        ,
      d_beta_0_d_c_0_ph      ,
      d_beta_d_c_1_ph        ,
      d_beta_0_d_c_1_ph      ,
      d_beta_d_c_2_ph        ,
      d_beta_0_d_c_2_ph      ,
      d_beta_d_c_3_ph        ,
      d_beta_0_d_c_3_ph      ,
      d_beta_d_c_4_ph        ,
      d_beta_0_d_c_4_ph      ,
      d_beta_d_p_0_h         ,
      d_beta_d_h_0_p         ,
      d_beta_0_d_p_h         ,
      d_beta_0_d_h_p         ,
      d_beta_0_d_p_0_h       ,
      d_beta_0_d_h_0_p       ,
      d_gamma_d_c_0_ph       ,
      d_gamma_0_d_c_0_ph     ,
      d_gamma_d_c_1_ph       ,
      d_gamma_0_d_c_1_ph     ,
      d_gamma_d_c_2_ph       ,
      d_gamma_0_d_c_2_ph     ,
      d_gamma_d_c_3_ph       ,
      d_gamma_0_d_c_3_ph     ,
      d_gamma_d_c_4_ph       ,
      d_gamma_0_d_c_4_ph     ,
      d_gamma_d_p_0_h        ,
      d_gamma_d_h_0_p        ,
      d_gamma_0_d_p_h        ,
      d_gamma_0_d_h_p        ,
      d_gamma_0_d_p_0_h      ,
      d_gamma_0_d_h_0_p      ,
      d_rho_l_sat_d_c_0_ph   ,
      d_rho_l_sat_0_d_c_0_ph ,
      d_rho_l_sat_d_c_1_ph   ,
      d_rho_l_sat_0_d_c_1_ph ,
      d_rho_l_sat_d_c_2_ph   ,
      d_rho_l_sat_0_d_c_2_ph ,
      d_rho_l_sat_d_c_3_ph   ,
      d_rho_l_sat_0_d_c_3_ph ,
      d_rho_l_sat_d_c_4_ph   ,
      d_rho_l_sat_0_d_c_4_ph ,
      d_rho_l_sat_d_p_0_h    ,
      d_rho_l_sat_d_h_0_p    ,
      d_rho_l_sat_0_d_p_h    ,
      d_rho_l_sat_0_d_h_p    ,
      d_rho_l_sat_0_d_p_0_h  ,
      d_rho_l_sat_0_d_h_0_p  ,
      d_rho_v_sat_d_c_0_ph   ,
      d_rho_v_sat_0_d_c_0_ph ,
      d_rho_v_sat_d_c_1_ph   ,
      d_rho_v_sat_0_d_c_1_ph ,
      d_rho_v_sat_d_c_2_ph   ,
      d_rho_v_sat_0_d_c_2_ph ,
      d_rho_v_sat_d_c_3_ph   ,
      d_rho_v_sat_0_d_c_3_ph ,
      d_rho_v_sat_d_c_4_ph   ,
      d_rho_v_sat_0_d_c_4_ph ,
      d_rho_v_sat_d_p_0_h    ,
      d_rho_v_sat_d_h_0_p    ,
      d_rho_v_sat_0_d_p_h    ,
      d_rho_v_sat_0_d_h_p    ,
      d_rho_v_sat_0_d_p_0_h  ,
      d_rho_v_sat_0_d_h_0_p  ,
      d_h_l_sat_d_c_0_ph     ,
      d_h_l_sat_0_d_c_0_ph   ,
      d_h_l_sat_d_c_1_ph     ,
      d_h_l_sat_0_d_c_1_ph   ,
      d_h_l_sat_d_c_2_ph     ,
      d_h_l_sat_0_d_c_2_ph   ,
      d_h_l_sat_d_c_3_ph     ,
      d_h_l_sat_0_d_c_3_ph   ,
      d_h_l_sat_d_c_4_ph     ,
      d_h_l_sat_0_d_c_4_ph   ,
      d_h_l_sat_d_p_0_h      ,
      d_h_l_sat_d_h_0_p      ,
      d_h_l_sat_0_d_p_h      ,
      d_h_l_sat_0_d_h_p      ,
      d_h_l_sat_0_d_p_0_h    ,
      d_h_l_sat_0_d_h_0_p    ,
      d_h_v_sat_d_c_0_ph     ,
      d_h_v_sat_0_d_c_0_ph   ,
      d_h_v_sat_d_c_1_ph     ,
      d_h_v_sat_0_d_c_1_ph   ,
      d_h_v_sat_d_c_2_ph     ,
      d_h_v_sat_0_d_c_2_ph   ,
      d_h_v_sat_d_c_3_ph     ,
      d_h_v_sat_0_d_c_3_ph   ,
      d_h_v_sat_d_c_4_ph     ,
      d_h_v_sat_0_d_c_4_ph   ,
      d_h_v_sat_d_p_0_h      ,
      d_h_v_sat_d_h_0_p      ,
      d_h_v_sat_0_d_p_h      ,
      d_h_v_sat_0_d_h_p      ,
      d_h_v_sat_0_d_p_0_h    ,
      d_h_v_sat_0_d_h_0_p    ,
      d_cp_l_sat_d_c_0_ph    ,
      d_cp_l_sat_0_d_c_0_ph  ,
      d_cp_l_sat_d_c_1_ph    ,
      d_cp_l_sat_0_d_c_1_ph  ,
      d_cp_l_sat_d_c_2_ph    ,
      d_cp_l_sat_0_d_c_2_ph  ,
      d_cp_l_sat_d_c_3_ph    ,
      d_cp_l_sat_0_d_c_3_ph  ,
      d_cp_l_sat_d_c_4_ph    ,
      d_cp_l_sat_0_d_c_4_ph  ,
      d_cp_l_sat_d_p_0_h     ,
      d_cp_l_sat_d_h_0_p     ,
      d_cp_l_sat_0_d_p_h     ,
      d_cp_l_sat_0_d_h_p     ,
      d_cp_l_sat_0_d_p_0_h   ,
      d_cp_l_sat_0_d_h_0_p   ,
      d_cp_v_sat_d_c_0_ph    ,
      d_cp_v_sat_0_d_c_0_ph  ,
      d_cp_v_sat_d_c_1_ph    ,
      d_cp_v_sat_0_d_c_1_ph  ,
      d_cp_v_sat_d_c_2_ph    ,
      d_cp_v_sat_0_d_c_2_ph  ,
      d_cp_v_sat_d_c_3_ph    ,
      d_cp_v_sat_0_d_c_3_ph  ,
      d_cp_v_sat_d_c_4_ph    ,
      d_cp_v_sat_0_d_c_4_ph  ,
      d_cp_v_sat_d_p_0_h     ,
      d_cp_v_sat_d_h_0_p     ,
      d_cp_v_sat_0_d_p_h     ,
      d_cp_v_sat_0_d_h_p     ,
      d_cp_v_sat_0_d_p_0_h   ,
      d_cp_v_sat_0_d_h_0_p   ,
      d_T_sat_d_c_0_ph       ,
      d_T_sat_0_d_c_0_ph     ,
      d_T_sat_d_c_1_ph       ,
      d_T_sat_0_d_c_1_ph     ,
      d_T_sat_d_c_2_ph       ,
      d_T_sat_0_d_c_2_ph     ,
      d_T_sat_d_c_3_ph       ,
      d_T_sat_0_d_c_3_ph     ,
      d_T_sat_d_c_4_ph       ,
      d_T_sat_0_d_c_4_ph     ,
      d_T_sat_d_p_0_h        ,
      d_T_sat_d_h_0_p        ,
      d_T_sat_0_d_p_h        ,
      d_T_sat_0_d_h_p        ,
      d_T_sat_0_d_p_0_h      ,
      d_T_sat_0_d_h_0_p      ,
      d_p_0_d_p_h            ,
      d_p_0_d_h_p            ,
      d_p_0_d_c_0_ph         ,
      d_p_0_d_c_1_ph         ,
      d_p_0_d_c_2_ph         ,
      d_p_0_d_c_3_ph         ,
      d_p_0_d_c_4_ph         ,
      d_h_0_d_p_h            ,
      d_h_0_d_h_p            ,
      d_h_0_d_c_0_ph         ,
      d_h_0_d_c_1_ph         ,
      d_h_0_d_c_2_ph         ,
      d_h_0_d_c_3_ph         ,
      d_h_0_d_c_4_ph         ,
      d_h_d_c_1_pT           ,
      d_h_d_c_2_pT           ,
      d_h_d_c_3_pT           ,
      d_h_d_c_4_pT           ,
      d_dncv_d_p_h           ,
      d_dncv_d_h_p           ,
      d_rnc_d_c_0_ph         ,
      d_rnc_d_c_1_ph         ,
      d_rnc_d_c_2_ph         ,
      d_rnc_d_c_3_ph         ,
      d_rnc_d_c_4_ph         ,
      d_mnc_d_c_0_ph         ,
      d_mnc_d_c_1_ph         ,
      d_mnc_d_c_2_ph         ,
      d_mnc_d_c_3_ph         ,
      d_mnc_d_c_4_ph         ,
      d_dncv_d_c_0_ph        ,
      d_dncv_d_c_1_ph        ,
      d_dncv_d_c_2_ph        ,
      d_dncv_d_c_3_ph        ,
      d_dncv_d_c_4_ph        ,
      d_mu_0_d_T_p           ,
      d_lambda_0_d_T_p       ,

      d2_T_sat_0_d_p_0_d_p_0 = d_lambda_0_d_T_p +1,
      lastCamixProperty = d2_T_sat_0_d_p_0_d_p_0

    };
  enum EOS_limcamixprop
    { EOS_TCMIPROP     = c_0 ,
      EOS_TCMIPROPDER  = d_T_d_c_0_ph ,
      EOS_TCMIPROPDER2 = d2_T_sat_0_d_p_0_d_p_0
    };
    
   
  EOS_camixprop nam2num_camixprop(const char* const name)   ;
  EOS_camixprop nam2num_dcamixprop(const char* const name)  ;
  EOS_camixprop nam2num_d2camixprop(const char* const name) ;

}
#include "EOS/API/camix_properties_i.hxx"
#endif 
