#!/bin/bash

# work directory
dirt=$1
# file
index_eos=$2

diro=`pwd`
cd $dirt

if [ -f ${index_eos}.conv   ]; then  rm ${index_eos}.conv   ; fi

list=
while read line  
do
        if [ ! -z "$line" ] ; then
                method=`echo $line | awk '{print $1}'`
                reference=`echo $line | awk '{print $2}'`
                fluid=`echo $line | awk '{print $4}'`
                phase=
                sreference=$reference
                smethod=$method
                if ( echo $reference | grep -iq Liquid ) ; then
                        phase=LIQUID
                        sreference=`echo $reference | sed 's/Liquid//i'`
                elif ( echo $reference | grep -iq Vapor ) ; then
                        phase=VAPOR
                        sreference=`echo $reference | sed 's/Vapor//i'`
                elif ( echo $reference | grep -iq Incondensable ) ; then
                        phase=INCONDENSABLE
                        sreference=`echo $reference | sed 's/Incondensable//i'`
                fi
                if [ -f methods.rules ] ; then
                        smethod=`echo $smethod | sed -f methods.rules`
                fi
#               if [ -f references.rules ] ; then
#                       sreference=`echo $sreference | sed -f references.rules`
#               fi
                smethod=`echo $smethod | cut -c -8 | tr [a-z.] [A-Z_]`

                sreference_ref=$sreference
                sreference=`echo $sreference | cut -c -8 | tr [a-z.] [A-Z_]`
                sreference=$sreference$phase
                i=0
                lista="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                while ( echo $list | grep -q "^$smethod $sreference$" ) 
                do
                   i=`expr $i + 1`
                   ic=`echo $lista | cut -c $i-$i`
                   sreference=`echo $sreference | cut -c -7`"$ic"
                   if [ $i -eq 36 ]; then break ; fi
                done
                if [ $i -eq 36 ]; then
                   echo "In entry $method-$reference" >&2
                   echo "Found:" >&2
                   echo -e $list | grep "^$smethod ${sreference_ref}$" >&2
                   echo "$smethod ${sreference_ref} duplicate. Exiting." >&2
                   exit 1
                fi

                list="$list\n$smethod $sreference"
                echo "$method $reference $smethod $fluid $sreference" >> ${index_eos}.conv
        fi
done < ${index_eos}
exit 0
cd $diro
